### ISSUE TITLE
PostProcessor doesn't replace existing file

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#1215]
**Branch/Commit:** Develop
**OS:** ubuntu 14.04
**What you did:** Snatch `Marvels.Luke.Cage.S01E03.Whos.Gonna.Take.the.Weight.720p.WEBRip.x264-TheRival.mp4` and waited for it to PP. Then snatched `Marvels.Luke.Cage.S01E03.720p.WEBRip.x264-SKGTV.mkv`
**What happened:** It did not PP the 2nd snatch
**What you expected:** For it to PP the 2nd snatch and overwridde the first download
**Logs:**
```
2016-09-30 22:20:19 INFO     POSTPROCESSOR :: [1ca7490] Processing /media/extssd/download/programas/Marvels.Luke.Cage.S01E03.720p.WEBRip.x264-SKGTV.mkv (Torrent)
2016-09-30 22:20:19 DEBUG    POSTPROCESSOR :: [1ca7490] Analyzing name Marvels.Luke.Cage.S01E03.720p.WEBRip.x264-SKGTV.mkv
2016-09-30 22:20:19 DEBUG    POSTPROCESSOR :: [1ca7490] Using cached parse result for Marvels.Luke.Cage.S01E03.720p.WEBRip.x264-SKGTV.mkv
2016-09-30 22:20:19 DEBUG    POSTPROCESSOR :: [1ca7490] Retrieving episode object for 1x3
2016-09-30 22:20:19 DEBUG    POSTPROCESSOR :: [1ca7490] Snatch history had a quality in it, using that: 720p WEB-DL
2016-09-30 22:20:19 DEBUG    POSTPROCESSOR :: [1ca7490] Quality of the episode we are processing: 720p WEB-DL
2016-09-30 22:20:19 DEBUG    POSTPROCESSOR :: [1ca7490] This episode is a priority download: False
2016-09-30 22:20:19 DEBUG    POSTPROCESSOR :: [1ca7490] File /media/extssd/Shows/Marvel's Luke Cage/Season 01/Marvels.Luke.Cage.S01E03.Whos.Gonna.Take.the.Weight.720p.WEB-DL.x264-TheRival.mp4 is smaller than /media/extssd/download/programas/Marvels.Luke.Cage.S01E03.720p.WEBRip.x264-SKGTV.mkv
2016-09-30 22:20:19 INFO     POSTPROCESSOR :: [1ca7490] File exists and new file quality is not in a preferred quality list, marking it unsafe to replace
2016-09-30 22:20:19 WARNING  POSTPROCESSOR :: [1ca7490] Processing failed for /media/extssd/download/programas/Marvels.Luke.Cage.S01E03.720p.WEBRip.x264-SKGTV.mkv:
```

_**Issue breakdown:**_ It is caused here https://github.com/pymedusa/SickRage/blob/develop/medusa/postProcessor.py#L1017-L1040 , to me what would make sense is only do the prefferd quality check if it's not in snatched state. Becouse if it is in snatched the one to be PP is the one user want's

**Comment by NicoLeOca** [comment]
I had the same issue a few days ago too

**Comment by NicoLeOca** [comment]
an example of this one:
![image](https://cloud.githubusercontent.com/assets/9487685/19325622/4d0dc64e-90c7-11e6-9a36-a8198f39fda9.png)

the whole bluray version is the 2nd arriving and all web-dl version should have been deleted

full logs:
https://gist.github.com/NicoLeOca/ef4a0417470b7d1e536e9ecd00d78f83

**Comment by NicoLeOca** [comment]
as mentionned here
https://github.com/pymedusa/Medusa/issues/1248
and following @duramato comment, the status of these were not on snatch but only on downloaded.

**Comment by medariox** [comment]
This should be fixed with: https://github.com/pymedusa/Medusa/pull/1264

**Comment by NicoLeOca** [comment]
@medariox 
this issue isn't fixed; I still have both files in the folder

I am using last develop on windows
can you please have a look at it

2016-10-23 19:26:42 INFO     Thread-26 :: [3d784e1] [C:\Users\**********\Downloads\AutoDL\Arrested.Development.S04.1080p.WEB-DL.DD+.5.1.x264-TrollHD\_unpack : Being unpacked]
2016-10-23 19:26:42 INFO     Thread-26 :: [3d784e1] I did encounter some unprocessable items: 
2016-10-23 19:26:42 INFO     Thread-26 :: [3d784e1] Successfully processed
2016-10-23 19:26:42 INFO     Thread-26 :: [3d784e1] Not deleting folder C:\Users\**********\Downloads\AutoDL\Arrested.Development.S04.1080p.WEB-DL.DD+.5.1.x264-TrollHD found the following files: [u'_unpack']
2016-10-23 19:26:42 DEBUG    Thread-26 :: [3d784e1] Parsed 'C:\Users\**********\Downloads\AutoDL\Arrested.Development.S04.1080p.WEB-DL.DD+.5.1.x264-TrollHD' into title: Arrested Development, season: 4, screen_size: 1080p, format: WEB-DL, audio_codec: DolbyDigital, audio_channels: 5.1, video_codec: h264, release_group: TrollHD, type: episode, absolute_episode: [], quality: 1080p WEB-DL, episode: []
2016-10-23 19:26:42 DEBUG    Thread-26 :: [3d784e1] Unable to match _unpack to a show in your database. Parser result: title: unpack, type: episode, absolute_episode: [], quality: Unknown, episode: [], season: None
2016-10-23 19:26:42 DEBUG    Thread-26 :: [3d784e1] Processing folder C:\Users\**********\Downloads\AutoDL\Arrested.Development.S04.1080p.WEB-DL.DD+.5.1.x264-TrollHD
2016-10-23 19:26:42 DEBUG    Thread-26 :: [3d784e1] The directory name indicates that this release is in the process of being unpacked.
2016-10-23 19:26:42 DEBUG    Thread-26 :: [3d784e1] Processing folder C:\Users\**********\Downloads\AutoDL\Arrested.Development.S04.1080p.WEB-DL.DD+.5.1.x264-TrollHD\_unpack
2016-10-23 19:26:42 INFO     Thread-26 :: [3d784e1] Not deleting folder C:\Users\**********\Downloads\AutoDL\arrested.development.s03e07.1080p.bluray-bia.r00.e1b1df8b found the following files: [u'arrested.development.s03e07.1080p.bluray.x264-bia.mkv']
2016-10-23 19:26:42 DEBUG    Thread-26 :: [3d784e1] No subtitles associated. Postponing the post-process of this file: arrested.development.s03e07.1080p.bluray.x264-bia.mkv
2016-10-23 19:26:42 DEBUG    Thread-26 :: [3d784e1] No associated files for C:\Users\**********\Downloads\AutoDL\arrested.development.s03e07.1080p.bluray-bia.r00.e1b1df8b\arrested.development.s03e07.1080p.bluray.x264-bia.mkv were found during this pass
2016-10-23 19:26:41 DEBUG    Thread-26 :: [3d784e1] Parsed 'C:\Users\**********\Downloads\AutoDL\arrested.development.s03e07.1080p.bluray-bia.r00.e1b1df8b\arrested.development.s03e07.1080p.bluray.x264-bia.mkv' into title: arrested development, season: 3, episode: [7], screen_size: 1080p, format: BluRay, crc32: e1b1df8b, video_codec: h264, release_group: bia, container: mkv, mimetype: video/x-matroska, type: episode, absolute_episode: [], quality: 1080p BluRay
2016-10-23 19:26:41 DEBUG    Thread-26 :: [3d784e1] Parsed 'arrested.development.s03e07.1080p.bluray.x264-bia.mkv' into title: arrested development, season: 3, episode: [7], screen_size: 1080p, format: BluRay, video_codec: h264, release_group: bia, container: mkv, mimetype: video/x-matroska, type: episode, absolute_episode: [], quality: 1080p BluRay
2016-10-23 19:26:41 DEBUG    Thread-26 :: [3d784e1] Processing folder C:\Users\**********\Downloads\AutoDL\arrested.development.s03e07.1080p.bluray-bia.r00.e1b1df8b
2016-10-23 19:26:41 INFO     Thread-26 :: [3d784e1] Not deleting folder C:\Users\**********\Downloads\AutoDL\Arrested.Development.S02E01.1080p.BluRay.x264-BiA found the following files: [u'arrested.development.s02e01.1080p.bluray.x264-bia.mkv']
2016-10-23 19:26:41 DEBUG    Thread-26 :: [3d784e1] No subtitles associated. Postponing the post-process of this file: arrested.development.s02e01.1080p.bluray.x264-bia.mkv
2016-10-23 19:26:41 DEBUG    Thread-26 :: [3d784e1] No associated files for C:\Users\**********\Downloads\AutoDL\Arrested.Development.S02E01.1080p.BluRay.x264-BiA\arrested.development.s02e01.1080p.bluray.x264-bia.mkv were found during this pass
2016-10-23 19:26:40 DEBUG    Thread-26 :: [3d784e1] Using cached parse result for 'C:\Users\**********\Downloads\AutoDL\Arrested.Development.S02E01.1080p.BluRay.x264-BiA\arrested.development.s02e01.1080p.bluray.x264-bia.mkv'
2016-10-23 19:26:40 DEBUG    Thread-26 :: [3d784e1] Parsed 'arrested.development.s02e01.1080p.bluray.x264-bia.mkv' into title: arrested development, season: 2, episode: [1], screen_size: 1080p, format: BluRay, video_codec: h264, release_group: bia, container: mkv, mimetype: video/x-matroska, type: episode, absolute_episode: [], quality: 1080p BluRay
2016-10-23 19:26:40 DEBUG    Thread-26 :: [3d784e1] Processing folder C:\Users\**********\Downloads\AutoDL\Arrested.Development.S02E01.1080p.BluRay.x264-BiA
2016-10-23 19:26:40 DEBUG    Thread-26 :: [3d784e1] Deleted folder: C:\Users\**********\Downloads\AutoDL\arrested.development.s01e16.1080p.bluray-bia.r00.5a471b0f
2016-10-23 19:26:40 INFO     Thread-26 :: [3d784e1] Deleting folder (if it's empty): C:\Users\**********\Downloads\AutoDL\arrested.development.s01e16.1080p.bluray-bia.r00.5a471b0f
2016-10-23 19:26:40 INFO     Thread-26 :: [3d784e1] Processing succeeded for C:\Users\**********\Downloads\AutoDL\arrested.development.s01e16.1080p.bluray-bia.r00.5a471b0f\arrested.development.s01e16.1080p.bluray.x264-bia.mkv
2016-10-23 19:26:40 DEBUG    Thread-26 :: [3d784e1] PLEX: Updating hosts where TV section paths match the downloaded show: 10, 2
2016-10-23 19:26:40 DEBUG    Thread-26 :: [3d784e1] Pushbullet notification sent.
2016-10-23 19:26:40 DEBUG    Thread-26 :: [3d784e1] Pushbullet devices: ''
2016-10-23 19:26:40 DEBUG    Thread-26 :: [3d784e1] Pushbullet api: '**********'
2016-10-23 19:26:40 DEBUG    Thread-26 :: [3d784e1] Pushbullet message: u'Arrested Development - 1x16 - Altar Egos - 1080p BluRay'
2016-10-23 19:26:40 DEBUG    Thread-26 :: [3d784e1] Pushbullet event: u'Download Finished : Arrested Development - 1x16 - Altar Egos - 1080p BluRay'
2016-10-23 19:26:40 DEBUG    Thread-26 :: [3d784e1] Notification for NMJ scan update not enabled, skipping this notification
2016-10-23 19:26:40 DEBUG    Thread-26 :: [3d784e1] 72173: Formatting pattern: %SN - %Sx%0E - %EN - %QN -> Arrested Development - 1x16 - Altar Egos - 1080p BluRay
2016-10-23 19:26:40 DEBUG    Thread-26 :: [3d784e1] Found codec for Arrested Development Altar Egos
2016-10-23 19:26:40 DEBUG    Thread-26 :: [3d784e1] Parsed 'arrested.development.s01e16.1080p.bluray.x264-bia' into title: arrested development, season: 1, episode: [16], screen_size: 1080p, format: BluRay, video_codec: h264, release_group: bia, type: episode, absolute_episode: [], quality: 1080p BluRay
2016-10-23 19:26:40 DEBUG    Thread-26 :: [3d784e1] Parsed 'Z:\Series\Arrested Development\Season 01\arrested.development.s01e16.1080p.bluray.x264-bia' into season: 1, title: arrested development, episode: [16], screen_size: 1080p, format: BluRay, video_codec: h264, release_group: bia, type: episode, absolute_episode: [], quality: 1080p BluRay
2016-10-23 19:26:40 DEBUG    Thread-30 :: [3d784e1] git describe --tags --abbrev=0 3d784e1e77e78bf389935e0dc3c2ab27772eed78 : returned successful
2016-10-23 19:26:39 DEBUG    Thread-30 :: [3d784e1] Executing git describe --tags --abbrev=0 3d784e1e77e78bf389935e0dc3c2ab27772eed78 with your shell in C:\Medusa
2016-10-23 19:26:39 DEBUG    Thread-30 :: [3d784e1] git rev-parse HEAD : returned successful
2016-10-23 19:26:39 DEBUG    Thread-26 :: [3d784e1] Transaction with 1 queries executed
2016-10-23 19:26:39 DEBUG    Thread-26 :: [3d784e1] 72173: Setter sets location to Z:\Series\Arrested Development\Season 01\arrested.development.s01e16.1080p.bluray.x264-bia.mkv
2016-10-23 19:26:39 DEBUG    Thread-26 :: [3d784e1] Transaction with 1 queries executed
2016-10-23 19:26:39 INFO     Thread-26 :: [3d784e1] 72173: No subtitles found for Arrested Development S01E16
2016-10-23 19:26:39 DEBUG    Thread-26 :: [3d784e1] 72173: Saving last subtitles search to database
2016-10-23 19:26:39 DEBUG    Thread-26 :: [3d784e1] Episode already has all needed subtitles, skipping Arrested Development S01E16
2016-10-23 19:26:39 DEBUG    Thread-26 :: [3d784e1] 72173: Saving subtitles changes to database
2016-10-23 19:26:39 DEBUG    Thread-26 :: [3d784e1] 72173: Subtitle changes detected for this show Arrested Development S01E16. Current subtitles: [u'eng']
2016-10-23 19:26:39 DEBUG    Thread-26 :: [3d784e1] Video information cached under key medusa.subtitles:video|Z:\Series\Arrested Development\Season 01\arrested.development.s01e16.1080p.bluray.x264-bia.mkv
2016-10-23 19:26:39 DEBUG    Thread-30 :: [3d784e1] Executing git rev-parse HEAD with your shell in C:\Medusa
2016-10-23 19:26:39 DEBUG    Thread-26 :: [3d784e1] Attribute tvdb_id changed from None to 75851
2016-10-23 19:26:39 DEBUG    Thread-30 :: [3d784e1] git symbolic-ref -q HEAD : returned successful
2016-10-23 19:26:39 DEBUG    Thread-26 :: [3d784e1] Attribute title changed from None to Altar Egos
2016-10-23 19:26:39 DEBUG    Thread-26 :: [3d784e1] Refining using TVEpisode information.
2016-10-23 19:26:39 DEBUG    Thread-26 :: [3d784e1] Attribute year changed from None to 2003
2016-10-23 19:26:39 DEBUG    Thread-26 :: [3d784e1] Attribute series_imdb_id changed from None to tt0367279
2016-10-23 19:26:39 DEBUG    Thread-26 :: [3d784e1] Attribute series_tvdb_id changed from None to 72173
2016-10-23 19:26:39 DEBUG    Thread-26 :: [3d784e1] Attribute series changed from arrested development to Arrested Development
2016-10-23 19:26:39 DEBUG    Thread-26 :: [3d784e1] Refining using TVShow information.
2016-10-23 19:26:39 DEBUG    Thread-26 :: [3d784e1] No release name for Z:\Series\Arrested Development\Season 01\arrested.development.s01e16.1080p.bluray.x264-bia.mkv
2016-10-23 19:26:39 DEBUG    Thread-26 :: [3d784e1] Starting release refiner [extension=release, release_name=None, release_file=None]
2016-10-23 19:26:39 DEBUG    Thread-30 :: [3d784e1] Executing git symbolic-ref -q HEAD with your shell in C:\Medusa
2016-10-23 19:26:39 DEBUG    Thread-30 :: [3d784e1] Using: git
2016-10-23 19:26:39 DEBUG    Thread-30 :: [3d784e1] git version : returned successful
2016-10-23 19:26:39 DEBUG    Thread-30 :: [3d784e1] Executing git version with your shell in C:\Medusa
2016-10-23 19:26:39 DEBUG    Thread-30 :: [3d784e1] Checking if we can use git commands: git version
2016-10-23 19:26:39 DEBUG    Thread-26 :: [3d784e1] Scanning video Z:\Series\Arrested Development\Season 01\arrested.development.s01e16.1080p.bluray.x264-bia.mkv...
2016-10-23 19:26:39 DEBUG    Thread-26 :: [3d784e1] Cached video information under key medusa.subtitles:video|Z:\Series\Arrested Development\Season 01\arrested.development.s01e16.1080p.bluray.x264-bia.mkv was invalidated
2016-10-23 19:26:39 DEBUG    Thread-26 :: [3d784e1] 72173: Setter sets location to Z:\Series\Arrested Development\Season 01\arrested.development.s01e16.1080p.bluray.x264-bia.mkv
2016-10-23 19:26:39 DEBUG    Thread-26 :: [3d784e1] Moving file from C:\Users\**********\Downloads\AutoDL\arrested.development.s01e16.1080p.bluray-bia.r00.5a471b0f\arrested.development.s01e16.1080p.bluray.x264-bia.en.srt to Z:\Series\Arrested Development\Season 01\arrested.development.s01e16.1080p.bluray.x264-bia.en.srt 
2016-10-23 19:26:21 DEBUG    Thread-26 :: [3d784e1] Moving file from C:\Users\**********\Downloads\AutoDL\arrested.development.s01e16.1080p.bluray-bia.r00.5a471b0f\arrested.development.s01e16.1080p.bluray.x264-bia.mkv to Z:\Series\Arrested Development\Season 01\arrested.development.s01e16.1080p.bluray.x264-bia.mkv 
2016-10-23 19:26:21 DEBUG    Thread-26 :: [3d784e1] Found the following associated files for C:\Users\**********\Downloads\AutoDL\arrested.development.s01e16.1080p.bluray-bia.r00.5a471b0f\arrested.development.s01e16.1080p.bluray.x264-bia.mkv: [u'C:\\Users\\**********\\Downloads\\AutoDL\\arrested.development.s01e16.1080p.bluray-bia.r00.5a471b0f\\arrested.development.s01e16.1080p.bluray.x264-bia.en.srt']
2016-10-23 19:26:20 DEBUG    Thread-26 :: [3d784e1] Checking if the path Z:\Series\Arrested Development\Season 01 already exists
2016-10-23 19:26:20 DEBUG    Thread-26 :: [3d784e1] Destination folder for this episode: Z:\Series\Arrested Development\Season 01
2016-10-23 19:26:20 DEBUG    Thread-26 :: [3d784e1] 72173: Formatting pattern: Season %0S -> Season 01
2016-10-23 19:26:20 DEBUG    Thread-26 :: [3d784e1] Found codec for Arrested Development Altar Egos
2016-10-23 19:26:20 DEBUG    Thread-26 :: [3d784e1] Parsed 'arrested.development.s01e16.1080p.bluray.x264-bia' into title: arrested development, season: 1, episode: [16], screen_size: 1080p, format: BluRay, video_codec: h264, release_group: bia, type: episode, absolute_episode: [], quality: 1080p BluRay
2016-10-23 19:26:20 DEBUG    Thread-26 :: [3d784e1] 72173: Formatting pattern: %RN -> arrested.development.s01e16.1080p.bluray.x264-bia
2016-10-23 19:26:20 DEBUG    Thread-26 :: [3d784e1] Found codec for Arrested Development Altar Egos
2016-10-23 19:26:20 DEBUG    Thread-26 :: [3d784e1] Parsed 'arrested.development.s01e16.1080p.bluray.x264-bia' into title: arrested development, season: 1, episode: [16], screen_size: 1080p, format: BluRay, video_codec: h264, release_group: bia, type: episode, absolute_episode: [], quality: 1080p BluRay
2016-10-23 19:26:20 DEBUG    Thread-26 :: [3d784e1] Folder name (arrested.development.s01e16.1080p.bluray-bia.r00.5a471b0f) appears to be a valid release name. Using it.
2016-10-23 19:26:20 DEBUG    Thread-26 :: [3d784e1] Parsed 'arrested.development.s01e16.1080p.bluray-bia.r00.5a471b0f' into title: arrested development, season: 1, episode: [16], screen_size: 1080p, format: BluRay, release_group: bia, crc32: 5a471b0f, type: episode, absolute_episode: [], quality: 1080p BluRay
2016-10-23 19:26:20 DEBUG    Thread-26 :: [3d784e1] Found release name arrested.development.s01e16.1080p.bluray.x264-bia
2016-10-23 19:26:20 DEBUG    Thread-26 :: [3d784e1] Trying to determine free space on destination drive
2016-10-23 19:26:20 INFO     Thread-26 :: [3d784e1] This download is marked a priority download so I'm going to replace an existing file if I find one
2016-10-23 19:26:20 DEBUG    Thread-26 :: [3d784e1] There is no existing file so there's no worries about replacing it
2016-10-23 19:26:20 DEBUG    Thread-26 :: [3d784e1] This episode is a priority download: True
2016-10-23 19:26:20 DEBUG    Thread-26 :: [3d784e1] This episode was snatched last and isn't processed yet, processing now
2016-10-23 19:26:20 DEBUG    Thread-26 :: [3d784e1] Quality of the episode we are processing: 1080p BluRay
2016-10-23 19:26:20 DEBUG    Thread-26 :: [3d784e1] The episode file has a quality in it, using that: 1080p BluRay
2016-10-23 19:26:20 DEBUG    Thread-26 :: [3d784e1] Retrieving episode object for Arrested Development S01E16
2016-10-23 19:26:20 DEBUG    Thread-26 :: [3d784e1] Parsed 'arrested.development.s01e16.1080p.bluray.x264-bia.mkv' into title: arrested development, season: 1, episode: [16], screen_size: 1080p, format: BluRay, video_codec: h264, release_group: bia, container: mkv, mimetype: video/x-matroska, type: episode, absolute_episode: [], quality: 1080p BluRay
2016-10-23 19:26:19 DEBUG    Thread-26 :: [3d784e1] Analyzing name: arrested.development.s01e16.1080p.bluray.x264-bia.mkv
2016-10-23 19:26:19 INFO     Thread-26 :: [3d784e1] Processing C:\Users\**********\Downloads\AutoDL\arrested.development.s01e16.1080p.bluray-bia.r00.5a471b0f\arrested.development.s01e16.1080p.bluray.x264-bia.mkv (Torrent)
2016-10-23 19:26:19 INFO     Thread-26 :: [3d784e1] Found subtitles associated. Continuing the post-process of this file: arrested.development.s01e16.1080p.bluray.x264-bia.mkv
2016-10-23 19:26:19 DEBUG    Thread-26 :: [3d784e1] Found the following associated files for C:\Users\**********\Downloads\AutoDL\arrested.development.s01e16.1080p.bluray-bia.r00.5a471b0f\arrested.development.s01e16.1080p.bluray.x264-bia.mkv: [u'C:\\Users\\**********\\Downloads\\AutoDL\\arrested.development.s01e16.1080p.bluray-bia.r00.5a471b0f\\arrested.development.s01e16.1080p.bluray.x264-bia.en.srt']
2016-10-23 19:26:19 DEBUG    Thread-26 :: [3d784e1] Parsed 'C:\Users\**********\Downloads\AutoDL\arrested.development.s01e16.1080p.bluray-bia.r00.5a471b0f\arrested.development.s01e16.1080p.bluray.x264-bia.mkv' into title: arrested development, season: 1, episode: [16], screen_size: 1080p, format: BluRay, crc32: 5a471b0f, video_codec: h264, release_group: bia, container: mkv, mimetype: video/x-matroska, type: episode, absolute_episode: [], quality: 1080p BluRay
2016-10-23 19:26:19 DEBUG    Thread-26 :: [3d784e1] Found unwanted files: [u'arrested.development.s01e16.1080p.bluray.x264-bia.en.srt']
2016-10-23 19:26:19 DEBUG    Thread-26 :: [3d784e1] Parsed 'arrested.development.s01e16.1080p.bluray.x264-bia.mkv' into title: arrested development, season: 1, episode: [16], screen_size: 1080p, format: BluRay, video_codec: h264, release_group: bia, container: mkv, mimetype: video/x-matroska, type: episode, absolute_episode: [], quality: 1080p BluRay
2016-10-23 19:26:18 DEBUG    Thread-26 :: [3d784e1] Processing folder C:\Users\**********\Downloads\AutoDL\arrested.development.s01e16.1080p.bluray-bia.r00.5a471b0f
2016-10-23 19:26:18 DEBUG    Thread-26 :: [3d784e1] Deleted folder: C:\Users\**********\Downloads\AutoDL\Arrested.Development.S01E08.1080p.BluRay.x264-BiA
2016-10-23 19:26:18 INFO     Thread-26 :: [3d784e1] Deleting folder (if it's empty): C:\Users\**********\Downloads\AutoDL\Arrested.Development.S01E08.1080p.BluRay.x264-BiA
2016-10-23 19:26:18 INFO     Thread-26 :: [3d784e1] Processing succeeded for C:\Users\**********\Downloads\AutoDL\Arrested.Development.S01E08.1080p.BluRay.x264-BiA\arrested.development.s01e08.1080p.bluray.x264-bia.mkv
2016-10-23 19:26:18 DEBUG    Thread-26 :: [3d784e1] PLEX: Updating hosts where TV section paths match the downloaded show: 10, 2
2016-10-23 19:26:18 DEBUG    Thread-26 :: [3d784e1] Pushbullet notification sent.
2016-10-23 19:26:18 DEBUG    Thread-26 :: [3d784e1] Pushbullet devices: ''
2016-10-23 19:26:18 DEBUG    Thread-26 :: [3d784e1] Pushbullet api: '**********'
2016-10-23 19:26:18 DEBUG    Thread-26 :: [3d784e1] Pushbullet message: u'Arrested Development - 1x08 - My Mother, The Car - 1080p BluRay'
2016-10-23 19:26:18 DEBUG    Thread-26 :: [3d784e1] Pushbullet event: u'Download Finished : Arrested Development - 1x08 - My Mother, The Car - 1080p BluRay'
2016-10-23 19:26:18 DEBUG    Thread-26 :: [3d784e1] Notification for NMJ scan update not enabled, skipping this notification
2016-10-23 19:26:18 DEBUG    Thread-26 :: [3d784e1] 72173: Formatting pattern: %SN - %Sx%0E - %EN - %QN -> Arrested Development - 1x08 - My Mother, The Car - 1080p BluRay
2016-10-23 19:26:18 DEBUG    Thread-26 :: [3d784e1] Found codec for Arrested Development My Mother, The Car
2016-10-23 19:26:18 DEBUG    Thread-26 :: [3d784e1] Parsed 'arrested.development.s01e08.1080p.bluray.x264-bia' into title: arrested development, season: 1, episode: [8], screen_size: 1080p, format: BluRay, video_codec: h264, release_group: bia, type: episode, absolute_episode: [], quality: 1080p BluRay
2016-10-23 19:26:18 DEBUG    Thread-26 :: [3d784e1] Parsed 'Z:\Series\Arrested Development\Season 01\arrested.development.s01e08.1080p.bluray.x264-bia' into season: 1, title: arrested development, episode: [8], screen_size: 1080p, format: BluRay, video_codec: h264, release_group: bia, type: episode, absolute_episode: [], quality: 1080p BluRay
2016-10-23 19:26:18 DEBUG    Thread-26 :: [3d784e1] Transaction with 1 queries executed
2016-10-23 19:26:18 DEBUG    Thread-26 :: [3d784e1] 72173: Setter sets location to Z:\Series\Arrested Development\Season 01\arrested.development.s01e08.1080p.bluray.x264-bia.mkv
2016-10-23 19:26:18 DEBUG    Thread-26 :: [3d784e1] Transaction with 1 queries executed
2016-10-23 19:26:18 INFO     Thread-26 :: [3d784e1] 72173: No subtitles found for Arrested Development S01E08
2016-10-23 19:26:18 DEBUG    Thread-26 :: [3d784e1] 72173: Saving last subtitles search to database
2016-10-23 19:26:18 DEBUG    Thread-26 :: [3d784e1] Episode already has all needed subtitles, skipping Arrested Development S01E08
2016-10-23 19:26:18 DEBUG    Thread-26 :: [3d784e1] 72173: Saving subtitles changes to database
2016-10-23 19:26:18 DEBUG    Thread-26 :: [3d784e1] 72173: Subtitle changes detected for this show Arrested Development S01E08. Current subtitles: [u'eng']
2016-10-23 19:26:18 DEBUG    Thread-26 :: [3d784e1] Video information cached under key medusa.subtitles:video|Z:\Series\Arrested Development\Season 01\arrested.development.s01e08.1080p.bluray.x264-bia.mkv
2016-10-23 19:26:18 DEBUG    Thread-26 :: [3d784e1] Attribute tvdb_id changed from None to 75841
2016-10-23 19:26:18 DEBUG    Thread-26 :: [3d784e1] Attribute title changed from None to My Mother, The Car
2016-10-23 19:26:18 DEBUG    Thread-26 :: [3d784e1] Refining using TVEpisode information.
2016-10-23 19:26:18 DEBUG    Thread-26 :: [3d784e1] Attribute year changed from None to 2003
2016-10-23 19:26:18 DEBUG    Thread-26 :: [3d784e1] Attribute series_imdb_id changed from None to tt0367279
2016-10-23 19:26:18 DEBUG    Thread-26 :: [3d784e1] Attribute series_tvdb_id changed from None to 72173
2016-10-23 19:26:18 DEBUG    Thread-26 :: [3d784e1] Attribute series changed from arrested development to Arrested Development
2016-10-23 19:26:18 DEBUG    Thread-26 :: [3d784e1] Refining using TVShow information.
2016-10-23 19:26:18 DEBUG    Thread-26 :: [3d784e1] No release name for Z:\Series\Arrested Development\Season 01\arrested.development.s01e08.1080p.bluray.x264-bia.mkv
2016-10-23 19:26:18 DEBUG    Thread-26 :: [3d784e1] Starting release refiner [extension=release, release_name=None, release_file=None]
2016-10-23 19:26:17 DEBUG    Thread-26 :: [3d784e1] Scanning video Z:\Series\Arrested Development\Season 01\arrested.development.s01e08.1080p.bluray.x264-bia.mkv...
2016-10-23 19:26:17 DEBUG    Thread-26 :: [3d784e1] Cached video information under key medusa.subtitles:video|Z:\Series\Arrested Development\Season 01\arrested.development.s01e08.1080p.bluray.x264-bia.mkv was invalidated
2016-10-23 19:26:17 DEBUG    Thread-26 :: [3d784e1] 72173: Setter sets location to Z:\Series\Arrested Development\Season 01\arrested.development.s01e08.1080p.bluray.x264-bia.mkv
2016-10-23 19:26:17 DEBUG    Thread-26 :: [3d784e1] Moving file from C:\Users\**********\Downloads\AutoDL\Arrested.Development.S01E08.1080p.BluRay.x264-BiA\arrested.development.s01e08.1080p.bluray.x264-bia.en.srt to Z:\Series\Arrested Development\Season 01\arrested.development.s01e08.1080p.bluray.x264-bia.en.srt 
2016-10-23 19:25:59 DEBUG    Thread-26 :: [3d784e1] Moving file from C:\Users\**********\Downloads\AutoDL\Arrested.Development.S01E08.1080p.BluRay.x264-BiA\arrested.development.s01e08.1080p.bluray.x264-bia.mkv to Z:\Series\Arrested Development\Season 01\arrested.development.s01e08.1080p.bluray.x264-bia.mkv 
2016-10-23 19:25:59 DEBUG    Thread-26 :: [3d784e1] Found the following associated files for C:\Users\**********\Downloads\AutoDL\Arrested.Development.S01E08.1080p.BluRay.x264-BiA\arrested.development.s01e08.1080p.bluray.x264-bia.mkv: [u'C:\\Users\\**********\\Downloads\\AutoDL\\Arrested.Development.S01E08.1080p.BluRay.x264-BiA\\arrested.development.s01e08.1080p.bluray.x264-bia.en.srt']
2016-10-23 19:25:58 DEBUG    Thread-26 :: [3d784e1] Checking if the path Z:\Series\Arrested Development\Season 01 already exists
2016-10-23 19:25:58 DEBUG    Thread-26 :: [3d784e1] Destination folder for this episode: Z:\Series\Arrested Development\Season 01
2016-10-23 19:25:58 DEBUG    Thread-26 :: [3d784e1] 72173: Formatting pattern: Season %0S -> Season 01
2016-10-23 19:25:58 DEBUG    Thread-26 :: [3d784e1] Found codec for Arrested Development My Mother, The Car
2016-10-23 19:25:58 DEBUG    Thread-26 :: [3d784e1] Parsed 'arrested.development.s01e08.1080p.bluray.x264-bia' into title: arrested development, season: 1, episode: [8], screen_size: 1080p, format: BluRay, video_codec: h264, release_group: bia, type: episode, absolute_episode: [], quality: 1080p BluRay
2016-10-23 19:25:58 DEBUG    Thread-26 :: [3d784e1] 72173: Formatting pattern: %RN -> arrested.development.s01e08.1080p.bluray.x264-bia
2016-10-23 19:25:58 DEBUG    Thread-26 :: [3d784e1] Found codec for Arrested Development My Mother, The Car
2016-10-23 19:25:58 DEBUG    Thread-26 :: [3d784e1] Parsed 'arrested.development.s01e08.1080p.bluray.x264-bia' into title: arrested development, season: 1, episode: [8], screen_size: 1080p, format: BluRay, video_codec: h264, release_group: bia, type: episode, absolute_episode: [], quality: 1080p BluRay
2016-10-23 19:25:58 DEBUG    Thread-26 :: [3d784e1] Folder name (Arrested.Development.S01E08.1080p.BluRay.x264-BiA) appears to be a valid release name. Using it.
2016-10-23 19:25:58 DEBUG    Thread-26 :: [3d784e1] Using cached parse result for 'Arrested.Development.S01E08.1080p.BluRay.x264-BiA'
2016-10-23 19:25:58 DEBUG    Thread-26 :: [3d784e1] Found release name arrested.development.s01e08.1080p.bluray.x264-bia
2016-10-23 19:25:58 DEBUG    Thread-26 :: [3d784e1] Trying to determine free space on destination drive
2016-10-23 19:25:58 INFO     Thread-26 :: [3d784e1] This download is marked a priority download so I'm going to replace an existing file if I find one
2016-10-23 19:25:58 DEBUG    Thread-26 :: [3d784e1] There is no existing file so there's no worries about replacing it
2016-10-23 19:25:58 DEBUG    Thread-26 :: [3d784e1] This episode is a priority download: True
2016-10-23 19:25:58 DEBUG    Thread-26 :: [3d784e1] This episode was snatched last and isn't processed yet, processing now
2016-10-23 19:25:58 DEBUG    Thread-26 :: [3d784e1] Quality of the episode we are processing: 1080p BluRay
2016-10-23 19:25:58 DEBUG    Thread-26 :: [3d784e1] The episode file has a quality in it, using that: 1080p BluRay
2016-10-23 19:25:58 DEBUG    Thread-26 :: [3d784e1] Retrieving episode object for Arrested Development S01E08
2016-10-23 19:25:58 DEBUG    Thread-26 :: [3d784e1] Parsed 'arrested.development.s01e08.1080p.bluray.x264-bia.mkv' into title: arrested development, season: 1, episode: [8], screen_size: 1080p, format: BluRay, video_codec: h264, release_group: bia, container: mkv, mimetype: video/x-matroska, type: episode, absolute_episode: [], quality: 1080p BluRay
2016-10-23 19:25:58 DEBUG    Thread-26 :: [3d784e1] Analyzing name: arrested.development.s01e08.1080p.bluray.x264-bia.mkv
2016-10-23 19:25:58 INFO     Thread-26 :: [3d784e1] Processing C:\Users\**********\Downloads\AutoDL\Arrested.Development.S01E08.1080p.BluRay.x264-BiA\arrested.development.s01e08.1080p.bluray.x264-bia.mkv (Torrent)
2016-10-23 19:25:58 INFO     Thread-26 :: [3d784e1] Found subtitles associated. Continuing the post-process of this file: arrested.development.s01e08.1080p.bluray.x264-bia.mkv
2016-10-23 19:25:58 DEBUG    Thread-26 :: [3d784e1] Found the following associated files for C:\Users\**********\Downloads\AutoDL\Arrested.Development.S01E08.1080p.BluRay.x264-BiA\arrested.development.s01e08.1080p.bluray.x264-bia.mkv: [u'C:\\Users\\**********\\Downloads\\AutoDL\\Arrested.Development.S01E08.1080p.BluRay.x264-BiA\\arrested.development.s01e08.1080p.bluray.x264-bia.en.srt']
2016-10-23 19:25:57 DEBUG    Thread-26 :: [3d784e1] Parsed 'C:\Users\**********\Downloads\AutoDL\Arrested.Development.S01E08.1080p.BluRay.x264-BiA\arrested.development.s01e08.1080p.bluray.x264-bia.mkv' into season: 1, episode: [8], screen_size: 1080p, format: BluRay, video_codec: h264, title: arrested development, release_group: bia, container: mkv, mimetype: video/x-matroska, type: episode, absolute_episode: [], quality: 1080p BluRay
2016-10-23 19:25:57 DEBUG    Thread-26 :: [3d784e1] Found unwanted files: [u'arrested.development.s01e08.1080p.bluray.x264-bia.en.srt']
2016-10-23 19:25:57 DEBUG    Thread-26 :: [3d784e1] Parsed 'arrested.development.s01e08.1080p.bluray.x264-bia.mkv' into title: arrested development, season: 1, episode: [8], screen_size: 1080p, format: BluRay, video_codec: h264, release_group: bia, container: mkv, mimetype: video/x-matroska, type: episode, absolute_episode: [], quality: 1080p BluRay
2016-10-23 19:25:57 DEBUG    Thread-26 :: [3d784e1] Processing folder C:\Users\**********\Downloads\AutoDL\Arrested.Development.S01E08.1080p.BluRay.x264-BiA
2016-10-23 19:25:57 DEBUG    Thread-26 :: [3d784e1] Deleted folder: C:\Users\**********\Downloads\AutoDL\Arrested.Development.S01E04.1080p.BluRay.x264-BiA
2016-10-23 19:25:57 INFO     Thread-26 :: [3d784e1] Deleting folder (if it's empty): C:\Users\**********\Downloads\AutoDL\Arrested.Development.S01E04.1080p.BluRay.x264-BiA
2016-10-23 19:25:57 INFO     Thread-26 :: [3d784e1] Processing succeeded for C:\Users\**********\Downloads\AutoDL\Arrested.Development.S01E04.1080p.BluRay.x264-BiA\arrested.development.s01e05.1080p.bluray.x264-bia.mkv
2016-10-23 19:25:57 DEBUG    Thread-26 :: [3d784e1] PLEX: Updating hosts where TV section paths match the downloaded show: 10, 2
2016-10-23 19:25:57 DEBUG    Thread-26 :: [3d784e1] Pushbullet notification sent.
2016-10-23 19:25:56 DEBUG    Thread-26 :: [3d784e1] Pushbullet devices: ''
2016-10-23 19:25:56 DEBUG    Thread-26 :: [3d784e1] Pushbullet api: '**********'
2016-10-23 19:25:56 DEBUG    Thread-26 :: [3d784e1] Pushbullet message: u'Arrested Development - 1x05 - Charity Drive - 1080p BluRay'
2016-10-23 19:25:56 DEBUG    Thread-26 :: [3d784e1] Pushbullet event: u'Download Finished : Arrested Development - 1x05 - Charity Drive - 1080p BluRay'
2016-10-23 19:25:56 DEBUG    Thread-26 :: [3d784e1] Notification for NMJ scan update not enabled, skipping this notification
2016-10-23 19:25:56 DEBUG    Thread-26 :: [3d784e1] 72173: Formatting pattern: %SN - %Sx%0E - %EN - %QN -> Arrested Development - 1x05 - Charity Drive - 1080p BluRay
2016-10-23 19:25:56 DEBUG    Thread-26 :: [3d784e1] Found codec for Arrested Development Charity Drive
2016-10-23 19:25:56 DEBUG    Thread-26 :: [3d784e1] Parsed 'arrested.development.s01e05.1080p.bluray.x264-bia' into title: arrested development, season: 1, episode: [5], screen_size: 1080p, format: BluRay, video_codec: h264, release_group: bia, type: episode, absolute_episode: [], quality: 1080p BluRay
2016-10-23 19:25:56 DEBUG    Thread-26 :: [3d784e1] Parsed 'Z:\Series\Arrested Development\Season 01\arrested.development.s01e05.1080p.bluray.x264-bia' into season: 1, title: arrested development, episode: [5], screen_size: 1080p, format: BluRay, video_codec: h264, release_group: bia, type: episode, absolute_episode: [], quality: 1080p BluRay
2016-10-23 19:25:56 DEBUG    Thread-26 :: [3d784e1] Transaction with 1 queries executed
2016-10-23 19:25:56 DEBUG    Thread-26 :: [3d784e1] 72173: Setter sets location to Z:\Series\Arrested Development\Season 01\arrested.development.s01e05.1080p.bluray.x264-bia.mkv
2016-10-23 19:25:56 DEBUG    Thread-26 :: [3d784e1] Transaction with 1 queries executed
2016-10-23 19:25:56 INFO     Thread-26 :: [3d784e1] 72173: No subtitles found for Arrested Development S01E05
2016-10-23 19:25:56 DEBUG    Thread-26 :: [3d784e1] 72173: Saving last subtitles search to database
2016-10-23 19:25:56 DEBUG    Thread-26 :: [3d784e1] Episode already has all needed subtitles, skipping Arrested Development S01E05
2016-10-23 19:25:56 DEBUG    Thread-26 :: [3d784e1] 72173: Saving subtitles changes to database
2016-10-23 19:25:56 DEBUG    Thread-26 :: [3d784e1] 72173: Subtitle changes detected for this show Arrested Development S01E05. Current subtitles: [u'eng']
2016-10-23 19:25:56 DEBUG    Thread-26 :: [3d784e1] Video information cached under key medusa.subtitles:video|Z:\Series\Arrested Development\Season 01\arrested.development.s01e05.1080p.bluray.x264-bia.mkv
2016-10-23 19:25:56 DEBUG    Thread-26 :: [3d784e1] Attribute tvdb_id changed from None to 75838
2016-10-23 19:25:56 DEBUG    Thread-26 :: [3d784e1] Attribute title changed from None to Charity Drive
2016-10-23 19:25:56 DEBUG    Thread-26 :: [3d784e1] Refining using TVEpisode information.
2016-10-23 19:25:56 DEBUG    Thread-26 :: [3d784e1] Attribute year changed from None to 2003
2016-10-23 19:25:56 DEBUG    Thread-26 :: [3d784e1] Attribute series_imdb_id changed from None to tt0367279
2016-10-23 19:25:56 DEBUG    Thread-26 :: [3d784e1] Attribute series_tvdb_id changed from None to 72173
2016-10-23 19:25:56 DEBUG    Thread-26 :: [3d784e1] Attribute series changed from arrested development to Arrested Development
2016-10-23 19:25:56 DEBUG    Thread-26 :: [3d784e1] Refining using TVShow information.
2016-10-23 19:25:56 DEBUG    Thread-26 :: [3d784e1] No release name for Z:\Series\Arrested Development\Season 01\arrested.development.s01e05.1080p.bluray.x264-bia.mkv
2016-10-23 19:25:56 DEBUG    Thread-26 :: [3d784e1] Starting release refiner [extension=release, release_name=None, release_file=None]
2016-10-23 19:25:55 DEBUG    Thread-26 :: [3d784e1] Scanning video Z:\Series\Arrested Development\Season 01\arrested.development.s01e05.1080p.bluray.x264-bia.mkv...
2016-10-23 19:25:55 DEBUG    Thread-26 :: [3d784e1] Cached video information under key medusa.subtitles:video|Z:\Series\Arrested Development\Season 01\arrested.development.s01e05.1080p.bluray.x264-bia.mkv was invalidated
2016-10-23 19:25:55 DEBUG    Thread-26 :: [3d784e1] 72173: Setter sets location to Z:\Series\Arrested Development\Season 01\arrested.development.s01e05.1080p.bluray.x264-bia.mkv
2016-10-23 19:25:55 DEBUG    Thread-26 :: [3d784e1] Moving file from C:\Users\**********\Downloads\AutoDL\Arrested.Development.S01E04.1080p.BluRay.x264-BiA\arrested.development.s01e05.1080p.bluray.x264-bia.en.srt to Z:\Series\Arrested Development\Season 01\arrested.development.s01e05.1080p.bluray.x264-bia.en.srt 
2016-10-23 19:25:37 DEBUG    Thread-26 :: [3d784e1] Moving file from C:\Users\**********\Downloads\AutoDL\Arrested.Development.S01E04.1080p.BluRay.x264-BiA\arrested.development.s01e05.1080p.bluray.x264-bia.mkv to Z:\Series\Arrested Development\Season 01\arrested.development.s01e05.1080p.bluray.x264-bia.mkv 
2016-10-23 19:25:37 DEBUG    Thread-26 :: [3d784e1] Found the following associated files for C:\Users\**********\Downloads\AutoDL\Arrested.Development.S01E04.1080p.BluRay.x264-BiA\arrested.development.s01e05.1080p.bluray.x264-bia.mkv: [u'C:\\Users\\**********\\Downloads\\AutoDL\\Arrested.Development.S01E04.1080p.BluRay.x264-BiA\\arrested.development.s01e05.1080p.bluray.x264-bia.en.srt']
2016-10-23 19:25:36 DEBUG    Thread-26 :: [3d784e1] Checking if the path Z:\Series\Arrested Development\Season 01 already exists
2016-10-23 19:25:36 DEBUG    Thread-26 :: [3d784e1] Destination folder for this episode: Z:\Series\Arrested Development\Season 01
2016-10-23 19:25:36 DEBUG    Thread-26 :: [3d784e1] 72173: Formatting pattern: Season %0S -> Season 01
2016-10-23 19:25:36 DEBUG    Thread-26 :: [3d784e1] Found codec for Arrested Development Charity Drive
2016-10-23 19:25:36 DEBUG    Thread-26 :: [3d784e1] Parsed 'arrested.development.s01e05.1080p.bluray.x264-bia' into title: arrested development, season: 1, episode: [5], screen_size: 1080p, format: BluRay, video_codec: h264, release_group: bia, type: episode, absolute_episode: [], quality: 1080p BluRay
2016-10-23 19:25:36 DEBUG    Thread-26 :: [3d784e1] 72173: Formatting pattern: %RN -> arrested.development.s01e05.1080p.bluray.x264-bia
2016-10-23 19:25:36 DEBUG    Thread-26 :: [3d784e1] Found codec for Arrested Development Charity Drive
2016-10-23 19:25:36 DEBUG    Thread-26 :: [3d784e1] Parsed 'arrested.development.s01e05.1080p.bluray.x264-bia' into title: arrested development, season: 1, episode: [5], screen_size: 1080p, format: BluRay, video_codec: h264, release_group: bia, type: episode, absolute_episode: [], quality: 1080p BluRay
2016-10-23 19:25:36 DEBUG    Thread-26 :: [3d784e1] Folder name (Arrested.Development.S01E04.1080p.BluRay.x264-BiA) appears to be a valid release name. Using it.
2016-10-23 19:25:36 DEBUG    Thread-26 :: [3d784e1] Parsed 'Arrested.Development.S01E04.1080p.BluRay.x264-BiA' into title: Arrested Development, season: 1, episode: [4], screen_size: 1080p, format: BluRay, video_codec: h264, release_group: BiA, type: episode, absolute_episode: [], quality: 1080p BluRay
2016-10-23 19:25:35 DEBUG    Thread-26 :: [3d784e1] Found release name arrested.development.s01e05.1080p.bluray.x264-bia
2016-10-23 19:25:35 DEBUG    Thread-26 :: [3d784e1] Trying to determine free space on destination drive
2016-10-23 19:25:35 INFO     Thread-26 :: [3d784e1] This download is marked a priority download so I'm going to replace an existing file if I find one
2016-10-23 19:25:35 DEBUG    Thread-26 :: [3d784e1] There is no existing file so there's no worries about replacing it
2016-10-23 19:25:35 DEBUG    Thread-26 :: [3d784e1] This episode is a priority download: True
2016-10-23 19:25:35 DEBUG    Thread-26 :: [3d784e1] This episode was snatched last and isn't processed yet, processing now
2016-10-23 19:25:35 DEBUG    Thread-26 :: [3d784e1] Quality of the episode we are processing: 1080p BluRay
2016-10-23 19:25:35 DEBUG    Thread-26 :: [3d784e1] The episode file has a quality in it, using that: 1080p BluRay
2016-10-23 19:25:35 DEBUG    Thread-26 :: [3d784e1] Retrieving episode object for Arrested Development S01E05
2016-10-23 19:25:35 DEBUG    Thread-26 :: [3d784e1] Parsed 'arrested.development.s01e05.1080p.bluray.x264-bia.mkv' into title: arrested development, season: 1, episode: [5], screen_size: 1080p, format: BluRay, video_codec: h264, release_group: bia, container: mkv, mimetype: video/x-matroska, type: episode, absolute_episode: [], quality: 1080p BluRay
2016-10-23 19:25:35 DEBUG    Thread-26 :: [3d784e1] Analyzing name: arrested.development.s01e05.1080p.bluray.x264-bia.mkv
2016-10-23 19:25:35 INFO     Thread-26 :: [3d784e1] Processing C:\Users\**********\Downloads\AutoDL\Arrested.Development.S01E04.1080p.BluRay.x264-BiA\arrested.development.s01e05.1080p.bluray.x264-bia.mkv (Torrent)
2016-10-23 19:25:35 INFO     Thread-26 :: [3d784e1] Found subtitles associated. Continuing the post-process of this file: arrested.development.s01e05.1080p.bluray.x264-bia.mkv
2016-10-23 19:25:35 DEBUG    Thread-26 :: [3d784e1] Found the following associated files for C:\Users\**********\Downloads\AutoDL\Arrested.Development.S01E04.1080p.BluRay.x264-BiA\arrested.development.s01e05.1080p.bluray.x264-bia.mkv: [u'C:\\Users\\**********\\Downloads\\AutoDL\\Arrested.Development.S01E04.1080p.BluRay.x264-BiA\\arrested.development.s01e05.1080p.bluray.x264-bia.en.srt']
2016-10-23 19:25:35 DEBUG    Thread-26 :: [3d784e1] Parsed 'C:\Users\**********\Downloads\AutoDL\Arrested.Development.S01E04.1080p.BluRay.x264-BiA\arrested.development.s01e05.1080p.bluray.x264-bia.mkv' into season: 1, screen_size: 1080p, format: BluRay, video_codec: h264, title: arrested development, episode: [5], release_group: bia, container: mkv, mimetype: video/x-matroska, type: episode, absolute_episode: [], quality: 1080p BluRay
2016-10-23 19:25:35 INFO     Thread-26 :: [3d784e1] Processing succeeded for C:\Users\**********\Downloads\AutoDL\Arrested.Development.S01E04.1080p.BluRay.x264-BiA\arrested.development.s01e04.1080p.bluray.x264-bia.mkv
2016-10-23 19:25:35 DEBUG    Thread-26 :: [3d784e1] PLEX: Updating hosts where TV section paths match the downloaded show: 10, 2
2016-10-23 19:25:35 DEBUG    Thread-26 :: [3d784e1] Pushbullet notification sent.
2016-10-23 19:25:34 DEBUG    Thread-26 :: [3d784e1] Pushbullet devices: ''
2016-10-23 19:25:34 DEBUG    Thread-26 :: [3d784e1] Pushbullet api: '**********'
2016-10-23 19:25:34 DEBUG    Thread-26 :: [3d784e1] Pushbullet message: u'Arrested Development - 1x04 - Key Decisions - 1080p BluRay'
2016-10-23 19:25:34 DEBUG    Thread-26 :: [3d784e1] Pushbullet event: u'Download Finished : Arrested Development - 1x04 - Key Decisions - 1080p BluRay'
2016-10-23 19:25:34 DEBUG    Thread-26 :: [3d784e1] Notification for NMJ scan update not enabled, skipping this notification
2016-10-23 19:25:34 DEBUG    Thread-26 :: [3d784e1] 72173: Formatting pattern: %SN - %Sx%0E - %EN - %QN -> Arrested Development - 1x04 - Key Decisions - 1080p BluRay
2016-10-23 19:25:34 DEBUG    Thread-26 :: [3d784e1] Found codec for Arrested Development Key Decisions
2016-10-23 19:25:34 DEBUG    Thread-26 :: [3d784e1] Parsed 'arrested.development.s01e04.1080p.bluray.x264-bia' into title: arrested development, season: 1, episode: [4], screen_size: 1080p, format: BluRay, video_codec: h264, release_group: bia, type: episode, absolute_episode: [], quality: 1080p BluRay
2016-10-23 19:25:34 DEBUG    Thread-26 :: [3d784e1] Parsed 'Z:\Series\Arrested Development\Season 01\arrested.development.s01e04.1080p.bluray.x264-bia' into season: 1, title: arrested development, episode: [4], screen_size: 1080p, format: BluRay, video_codec: h264, release_group: bia, type: episode, absolute_episode: [], quality: 1080p BluRay
2016-10-23 19:25:34 DEBUG    Thread-26 :: [3d784e1] Transaction with 1 queries executed
2016-10-23 19:25:34 DEBUG    Thread-26 :: [3d784e1] 72173: Setter sets location to Z:\Series\Arrested Development\Season 01\arrested.development.s01e04.1080p.bluray.x264-bia.mkv
2016-10-23 19:25:34 DEBUG    Thread-26 :: [3d784e1] Transaction with 1 queries executed
2016-10-23 19:25:34 INFO     Thread-26 :: [3d784e1] 72173: No subtitles found for Arrested Development S01E04
2016-10-23 19:25:34 DEBUG    Thread-26 :: [3d784e1] 72173: Saving last subtitles search to database
2016-10-23 19:25:34 DEBUG    Thread-26 :: [3d784e1] Episode already has all needed subtitles, skipping Arrested Development S01E04
2016-10-23 19:25:34 DEBUG    Thread-26 :: [3d784e1] 72173: Saving subtitles changes to database
2016-10-23 19:25:34 DEBUG    Thread-26 :: [3d784e1] 72173: Subtitle changes detected for this show Arrested Development S01E04. Current subtitles: [u'eng']
2016-10-23 19:25:34 DEBUG    Thread-26 :: [3d784e1] Video information cached under key medusa.subtitles:video|Z:\Series\Arrested Development\Season 01\arrested.development.s01e04.1080p.bluray.x264-bia.mkv
2016-10-23 19:25:34 DEBUG    Thread-26 :: [3d784e1] Attribute tvdb_id changed from None to 75837
2016-10-23 19:25:34 DEBUG    Thread-26 :: [3d784e1] Attribute title changed from None to Key Decisions
2016-10-23 19:25:34 DEBUG    Thread-26 :: [3d784e1] Refining using TVEpisode information.
2016-10-23 19:25:34 DEBUG    Thread-26 :: [3d784e1] Attribute year changed from None to 2003
2016-10-23 19:25:34 DEBUG    Thread-26 :: [3d784e1] Attribute series_imdb_id changed from None to tt0367279
2016-10-23 19:25:34 DEBUG    Thread-26 :: [3d784e1] Attribute series_tvdb_id changed from None to 72173
2016-10-23 19:25:34 DEBUG    Thread-26 :: [3d784e1] Attribute series changed from arrested development to Arrested Development
2016-10-23 19:25:34 DEBUG    Thread-26 :: [3d784e1] Refining using TVShow information.
2016-10-23 19:25:34 DEBUG    Thread-26 :: [3d784e1] No release name for Z:\Series\Arrested Development\Season 01\arrested.development.s01e04.1080p.bluray.x264-bia.mkv
2016-10-23 19:25:34 DEBUG    Thread-26 :: [3d784e1] Starting release refiner [extension=release, release_name=None, release_file=None]
2016-10-23 19:25:33 DEBUG    Thread-26 :: [3d784e1] Scanning video Z:\Series\Arrested Development\Season 01\arrested.development.s01e04.1080p.bluray.x264-bia.mkv...
2016-10-23 19:25:33 DEBUG    Thread-26 :: [3d784e1] Cached video information under key medusa.subtitles:video|Z:\Series\Arrested Development\Season 01\arrested.development.s01e04.1080p.bluray.x264-bia.mkv was invalidated
2016-10-23 19:25:33 DEBUG    Thread-26 :: [3d784e1] 72173: Setter sets location to Z:\Series\Arrested Development\Season 01\arrested.development.s01e04.1080p.bluray.x264-bia.mkv
2016-10-23 19:25:33 DEBUG    Thread-26 :: [3d784e1] Moving file from C:\Users\**********\Downloads\AutoDL\Arrested.Development.S01E04.1080p.BluRay.x264-BiA\arrested.development.s01e04.1080p.bluray.x264-bia.en.srt to Z:\Series\Arrested Development\Season 01\arrested.development.s01e04.1080p.bluray.x264-bia.en.srt 
2016-10-23 19:24:49 DEBUG    Thread-26 :: [3d784e1] Moving file from C:\Users\**********\Downloads\AutoDL\Arrested.Development.S01E04.1080p.BluRay.x264-BiA\arrested.development.s01e04.1080p.bluray.x264-bia.mkv to Z:\Series\Arrested Development\Season 01\arrested.development.s01e04.1080p.bluray.x264-bia.mkv 
2016-10-23 19:24:49 DEBUG    Thread-26 :: [3d784e1] Found the following associated files for C:\Users\**********\Downloads\AutoDL\Arrested.Development.S01E04.1080p.BluRay.x264-BiA\arrested.development.s01e04.1080p.bluray.x264-bia.mkv: [u'C:\\Users\\**********\\Downloads\\AutoDL\\Arrested.Development.S01E04.1080p.BluRay.x264-BiA\\arrested.development.s01e04.1080p.bluray.x264-bia.en.srt']
2016-10-23 19:24:48 DEBUG    Thread-26 :: [3d784e1] Checking if the path Z:\Series\Arrested Development\Season 01 already exists
2016-10-23 19:24:48 DEBUG    Thread-26 :: [3d784e1] Destination folder for this episode: Z:\Series\Arrested Development\Season 01
2016-10-23 19:24:48 DEBUG    Thread-26 :: [3d784e1] 72173: Formatting pattern: Season %0S -> Season 01
2016-10-23 19:24:48 DEBUG    Thread-26 :: [3d784e1] Found codec for Arrested Development Key Decisions
2016-10-23 19:24:48 DEBUG    Thread-26 :: [3d784e1] Parsed 'arrested.development.s01e04.1080p.bluray.x264-bia' into title: arrested development, season: 1, episode: [4], screen_size: 1080p, format: BluRay, video_codec: h264, release_group: bia, type: episode, absolute_episode: [], quality: 1080p BluRay
2016-10-23 19:24:48 DEBUG    Thread-26 :: [3d784e1] 72173: Formatting pattern: %RN -> arrested.development.s01e04.1080p.bluray.x264-bia
2016-10-23 19:24:48 DEBUG    Thread-26 :: [3d784e1] Found codec for Arrested Development Key Decisions
2016-10-23 19:24:47 DEBUG    Thread-26 :: [3d784e1] Parsed 'arrested.development.s01e04.1080p.bluray.x264-bia' into title: arrested development, season: 1, episode: [4], screen_size: 1080p, format: BluRay, video_codec: h264, release_group: bia, type: episode, absolute_episode: [], quality: 1080p BluRay
2016-10-23 19:24:47 DEBUG    Thread-26 :: [3d784e1] Folder name (Arrested.Development.S01E04.1080p.BluRay.x264-BiA) appears to be a valid release name. Using it.
2016-10-23 19:24:47 DEBUG    Thread-26 :: [3d784e1] Parsed 'Arrested.Development.S01E04.1080p.BluRay.x264-BiA' into title: Arrested Development, season: 1, episode: [4], screen_size: 1080p, format: BluRay, video_codec: h264, release_group: BiA, type: episode, absolute_episode: [], quality: 1080p BluRay
2016-10-23 19:24:47 DEBUG    Thread-26 :: [3d784e1] Found release name arrested.development.s01e04.1080p.bluray.x264-bia
2016-10-23 19:24:47 DEBUG    Thread-26 :: [3d784e1] Trying to determine free space on destination drive
2016-10-23 19:24:47 INFO     Thread-26 :: [3d784e1] This download is marked a priority download so I'm going to replace an existing file if I find one
2016-10-23 19:24:47 DEBUG    Thread-26 :: [3d784e1] There is no existing file so there's no worries about replacing it
2016-10-23 19:24:47 DEBUG    Thread-26 :: [3d784e1] This episode is a priority download: True
2016-10-23 19:24:47 DEBUG    Thread-26 :: [3d784e1] This episode was snatched last and isn't processed yet, processing now
2016-10-23 19:24:47 DEBUG    Thread-26 :: [3d784e1] Quality of the episode we are processing: 1080p BluRay
2016-10-23 19:24:47 DEBUG    Thread-26 :: [3d784e1] The episode file has a quality in it, using that: 1080p BluRay
2016-10-23 19:24:47 DEBUG    Thread-26 :: [3d784e1] Retrieving episode object for Arrested Development S01E04
2016-10-23 19:24:47 DEBUG    Thread-26 :: [3d784e1] Parsed 'arrested.development.s01e04.1080p.bluray.x264-bia.mkv' into title: arrested development, season: 1, episode: [4], screen_size: 1080p, format: BluRay, video_codec: h264, release_group: bia, container: mkv, mimetype: video/x-matroska, type: episode, absolute_episode: [], quality: 1080p BluRay
2016-10-23 19:24:47 DEBUG    Thread-26 :: [3d784e1] Analyzing name: arrested.development.s01e04.1080p.bluray.x264-bia.mkv
2016-10-23 19:24:47 INFO     Thread-26 :: [3d784e1] Processing C:\Users\**********\Downloads\AutoDL\Arrested.Development.S01E04.1080p.BluRay.x264-BiA\arrested.development.s01e04.1080p.bluray.x264-bia.mkv (Torrent)
2016-10-23 19:24:47 INFO     Thread-26 :: [3d784e1] Found subtitles associated. Continuing the post-process of this file: arrested.development.s01e04.1080p.bluray.x264-bia.mkv
2016-10-23 19:24:47 DEBUG    Thread-26 :: [3d784e1] Found the following associated files for C:\Users\**********\Downloads\AutoDL\Arrested.Development.S01E04.1080p.BluRay.x264-BiA\arrested.development.s01e04.1080p.bluray.x264-bia.mkv: [u'C:\\Users\\**********\\Downloads\\AutoDL\\Arrested.Development.S01E04.1080p.BluRay.x264-BiA\\arrested.development.s01e04.1080p.bluray.x264-bia.en.srt']
2016-10-23 19:24:47 DEBUG    Thread-26 :: [3d784e1] Parsed 'C:\Users\**********\Downloads\AutoDL\Arrested.Development.S01E04.1080p.BluRay.x264-BiA\arrested.development.s01e04.1080p.bluray.x264-bia.mkv' into season: 1, episode: [4], screen_size: 1080p, format: BluRay, video_codec: h264, title: arrested development, release_group: bia, container: mkv, mimetype: video/x-matroska, type: episode, absolute_episode: [], quality: 1080p BluRay
2016-10-23 19:24:47 DEBUG    Thread-26 :: [3d784e1] Found unwanted files: [u'arrested.development.s01e04.1080p.bluray.x264-bia.en.srt', u'arrested.development.s01e05.1080p.bluray.x264-bia.en.srt']
2016-10-23 19:24:47 DEBUG    Thread-26 :: [3d784e1] Parsed 'arrested.development.s01e04.1080p.bluray.x264-bia.mkv' into title: arrested development, season: 1, episode: [4], screen_size: 1080p, format: BluRay, video_codec: h264, release_group: bia, container: mkv, mimetype: video/x-matroska, type: episode, absolute_episode: [], quality: 1080p BluRay
2016-10-23 19:24:47 DEBUG    Thread-26 :: [3d784e1] Processing folder C:\Users\**********\Downloads\AutoDL\Arrested.Development.S01E04.1080p.BluRay.x264-BiA
2016-10-23 19:24:47 DEBUG    Thread-26 :: [3d784e1] Deluge Seedbox : No processable items found in the folder
2016-10-23 19:24:47 DEBUG    Thread-26 :: [3d784e1] Unable to match Deluge Seedbox to a show in your database. Parser result: title: Deluge Seedbox, type: episode, absolute_episode: [], quality: Unknown, episode: [], season: None
2016-10-23 19:24:47 DEBUG    Thread-26 :: [3d784e1] Processing folder Deluge Seedbox
2016-10-23 19:24:47 DEBUG    Thread-26 :: [3d784e1] Parsed 'Arrested.Development.S04.1080p.WEB-DL.DD+.5.1.x264-TrollHD' into title: Arrested Development, season: 4, screen_size: 1080p, format: WEB-DL, audio_codec: DolbyDigital, audio_channels: 5.1, video_codec: h264, release_group: TrollHD, type: episode, absolute_episode: [], quality: 1080p WEB-DL, episode: []
2016-10-23 19:24:47 DEBUG    Thread-26 :: [3d784e1] Unable to match _unpack to a show in your database. Parser result: title: unpack, type: episode, absolute_episode: [], quality: Unknown, episode: [], season: None
2016-10-23 19:24:46 DEBUG    Thread-26 :: [3d784e1] Processing folder Arrested.Development.S04.1080p.WEB-DL.DD+.5.1.x264-TrollHD
2016-10-23 19:24:46 DEBUG    Thread-26 :: [3d784e1] Parsed 'arrested.development.s03e07.1080p.bluray.x264-bia.mkv' into title: arrested development, season: 3, episode: [7], screen_size: 1080p, format: BluRay, video_codec: h264, release_group: bia, container: mkv, mimetype: video/x-matroska, type: episode, absolute_episode: [], quality: 1080p BluRay
2016-10-23 19:24:46 DEBUG    Thread-26 :: [3d784e1] Processing folder arrested.development.s03e07.1080p.bluray-bia.r00.e1b1df8b
2016-10-23 19:24:46 DEBUG    Thread-26 :: [3d784e1] Parsed 'arrested.development.s02e01.1080p.bluray.x264-bia.mkv' into title: arrested development, season: 2, episode: [1], screen_size: 1080p, format: BluRay, video_codec: h264, release_group: bia, container: mkv, mimetype: video/x-matroska, type: episode, absolute_episode: [], quality: 1080p BluRay
2016-10-23 19:24:46 DEBUG    Thread-26 :: [3d784e1] Processing folder Arrested.Development.S02E01.1080p.BluRay.x264-BiA
2016-10-23 19:24:46 DEBUG    Thread-26 :: [3d784e1] Parsed 'arrested.development.s01e16.1080p.bluray.x264-bia.mkv' into title: arrested development, season: 1, episode: [16], screen_size: 1080p, format: BluRay, video_codec: h264, release_group: bia, container: mkv, mimetype: video/x-matroska, type: episode, absolute_episode: [], quality: 1080p BluRay
2016-10-23 19:24:46 DEBUG    Thread-26 :: [3d784e1] Processing folder arrested.development.s01e16.1080p.bluray-bia.r00.5a471b0f
2016-10-23 19:24:46 DEBUG    Thread-26 :: [3d784e1] Parsed 'arrested.development.s01e08.1080p.bluray.x264-bia.mkv' into title: arrested development, season: 1, episode: [8], screen_size: 1080p, format: BluRay, video_codec: h264, release_group: bia, container: mkv, mimetype: video/x-matroska, type: episode, absolute_episode: [], quality: 1080p BluRay
2016-10-23 19:24:46 DEBUG    Thread-26 :: [3d784e1] Processing folder Arrested.Development.S01E08.1080p.BluRay.x264-BiA
2016-10-23 19:24:46 DEBUG    Thread-26 :: [3d784e1] Parsed 'arrested.development.s01e04.1080p.bluray.x264-bia.mkv' into title: arrested development, season: 1, episode: [4], screen_size: 1080p, format: BluRay, video_codec: h264, release_group: bia, container: mkv, mimetype: video/x-matroska, type: episode, absolute_episode: [], quality: 1080p BluRay
2016-10-23 19:24:46 DEBUG    Thread-26 :: [3d784e1] Processing folder Arrested.Development.S01E04.1080p.BluRay.x264-BiA
2016-10-23 19:24:46 DEBUG    Thread-26 :: [3d784e1] PostProcessing VideoInRar: 
2016-10-23 19:24:46 DEBUG    Thread-26 :: [3d784e1] PostProcessing RarContent: 
2016-10-23 19:24:46 DEBUG    Thread-26 :: [3d784e1] PostProcessing VideoFiles: []
2016-10-23 19:24:46 DEBUG    Thread-26 :: [3d784e1] PostProcessing Files: []
2016-10-23 19:24:46 DEBUG    Thread-26 :: [3d784e1] PostProcessing Dirs: [u'Arrested.Development.S01E04.1080p.BluRay.x264-BiA', u'Arrested.Development.S01E08.1080p.BluRay.x264-BiA', u'arrested.development.s01e16.1080p.bluray-bia.r00.5a471b0f', u'Arrested.Development.S02E01.1080p.BluRay.x264-BiA', u'arrested.development.s03e07.1080p.bluray-bia.r00.e1b1df8b', u'Arrested.Development.S04.1080p.WEB-DL.DD+.5.1.x264-TrollHD', u'Deluge Seedbox']
2016-10-23 19:24:46 INFO     Thread-26 :: [3d784e1] PostProcessing Path: C:\Users\**********\Downloads\AutoDL
2016-10-23 19:24:46 INFO     Thread-26 :: [3d784e1] Feature 'postpone post-processing if no subtitle available' is enabled
2016-10-23 19:24:46 DEBUG    Thread-26 :: [3d784e1] Processing folder C:\Users\**********\Downloads\AutoDL

**Comment by medariox** [comment]
@NicoLeOca 
Please open a new issue explaining what you did, what you expected and what happened instead.
