### ISSUE TITLE
Torrent file content empty?

### ISSUE THREAD

**Issue by wimpyrbx** [pymedusa/Medusa#1328]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

2016-10-26 02:44:50 WARNING  SNATCHQUEUE-MANUALSNATCH-194031 :: [ff5cfb9] Torrent file content is empty
2016-10-26 02:44:50 INFO     SNATCHQUEUE-MANUALSNATCH-194031 :: [ff5cfb9] Downloading Bobs.Burgers.S07E03.(1080p.WEB-DL.x265.HEVC.10bit.AAC.5.1.ImE).[UTR] with 1 seeders and 0 leechers from ExtraTorrent

Branch/Commit: develop
OS: windows
What you did: manually snatched from extratorrent (extratorrent.is used as custom url)
What happened: it did not download
What you expected: for it to download. download works when downloading manually from the site directly.
Logs:
```
PASTE LOGS HERE
```

**Comment by fernandog** [comment]
@wimpyrbx search your log for something like this:

"Downloading a result from Rarbg at https://torrentproject.se/torrent/D1E3C4********.torrent"

i guess the problem is the cache site. in this case torrentproject.

**Comment by wimpyrbx** [comment]
found the error..

2016-10-26 11:41:37 INFO     SNATCHQUEUE-MANUALSNATCH-194031 :: [9f9a897] Beginning to manual snatch release: Bobs.Burgers.S07E03.(1080p.WEB-DL.x265.HEVC.10bit.AAC.5.1.ImE).[UTR]
2016-10-26 11:41:37 INFO     SNATCHQUEUE-MANUALSNATCH-194031 :: [9f9a897] Downloading Bobs.Burgers.S07E03.(1080p.WEB-DL.x265.HEVC.10bit.AAC.5.1.ImE).[UTR] with 1 seeders and 0 leechers from ExtraTorrent
2016-10-26 11:41:37 DEBUG    SNATCHQUEUE-MANUALSNATCH-194031 :: [9f9a897] GET URL: http://extratorrent.cc/download/5253126/Bobs+Burgers+S07E03+%281080p+WEB-DL+x265+HEVC+10bit+AAC+5.1+ImE%29+%5BUTR%5D.torrent [Status: 404]
2016-10-26 11:41:37 DEBUG    SNATCHQUEUE-MANUALSNATCH-194031 :: [9f9a897] Requested url http://extratorrent.cc/download/5253126/Bobs+Burgers+S07E03+%281080p+WEB-DL+x265+HEVC+10bit+AAC+5.1+ImE%29+%5BUTR%5D.torrent returned status code 404: Not Found
2016-10-26 11:41:37 WARNING  SNATCHQUEUE-MANUALSNATCH-194031 :: [9f9a897] Torrent file content is empty

even tho i've changed custom url to extratorrent.is instead of extratorrent.cc (which is blocked here in Norway) it fetched using .cc domain. is it possible to change that?

**Comment by duramato** [comment]
Issue is here Afaik https://github.com/pymedusa/Medusa/blob/master/medusa/providers/torrent/html/extratorrent.py#L147 Its doing a join with the cc domain

**Comment by wimpyrbx** [comment]
would it then be possible, if a custom url for this tracker is supplied in config.. that it uses that instead of .cc?

**Comment by medariox** [comment]
Fixed in develop.

**Comment by jfairham1** [comment]
This issue still exists with numerous search providers. Its the only thing stopping me to switching to Medusa permanently from Sonaar

**Comment by jfairham1** [comment]
Download client - Deluge

Medusa Info: | Branch: masterCommit: d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebeVersion: v0.2.1Database: 44.9
Python Version: | 2.7.12 (default, Dec 4 2017, 14:50:18) [GCC 5.4.0 20160609]

2018-04-11 23:11:43 WARNING  SEARCHQUEUE-FORCED-342190 :: [d6eb72d] Torrent file content is empty: One.Strange.Rock.S01E02.1080p.AMZN.WEB-DL.DD+.5.1.H.264-NTb
2018-04-11 23:11:43 INFO     SEARCHQUEUE-FORCED-342190 :: [d6eb72d] Downloading One.Strange.Rock.S01E02.1080p.AMZN.WEB-DL.DD+.5.1.H.264-NTb with 26 seeders and 1 leechers and size 3.40 GB from PrivateHD
2018-04-11 23:11:43 INFO     SEARCHQUEUE-FORCED-342190 :: [HDTorrents] :: [d6eb72d] Performing season pack search for One Strange Rock
2018-04-11 23:11:43 INFO     SEARCHQUEUE-FORCED-342190 :: [HDTorrents] :: [d6eb72d] Performing episode search for One Strange Rock
2018-04-11 23:11:43 INFO     SEARCHQUEUE-FORCED-342190 :: [PrivateHD] :: [d6eb72d] Quality of One.Strange.Rock.S01E02.1080p.AMZN.WEB-DL.DD+.5.1.H.264-NTb is 1080p WEB-DL
2018-04-11 23:11:43 INFO     SEARCHQUEUE-FORCED-342190 :: [PrivateHD] :: [d6eb72d] Performing episode search for One Strange Rock
