### ISSUE TITLE
Torznab via Newnab issue

### ISSUE THREAD

**Issue by saitoh183** [pymedusa/Medusa#3149]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:** master/3f23fd272652b10cf781e3058fee50daf79f11b6
**OS:** Linux
**What you did:** manual and auto search of a episode
**What happened:** torrents snatched via newsnab (jackett indexer) are not created in blackhole folder. After a lenghty discussion on irc with @medusabot ,he/she stated that medusa basically thinks we are downloading an nzb. Like lots of people, i have always added jackett torznab link in the newsnab section because there was no torznab section when i was using sickrage and it always worked. Now i switch over to medusa and it was working at first and now it stopped working. This is really a deal breaker right now because my primary French torrent indexer, ethor.net is only accessible via jackett.

**Logs:**
```
2017-10-05 16:14:48 DEBUG    TORNADO :: [3f23fd2] API :: history: {'limit': '100', 'type': 'downloaded'}
2017-10-05 16:14:48 DEBUG    TORNADO :: [3f23fd2] API :: all kwargs: {'type': 'downloaded', 'cmd': 'history', 'limit': '100'}
2017-10-05 16:14:48 DEBUG    TORNADO :: [3f23fd2] API :: all args: ()
2017-10-05 16:14:48 DEBUG    TORNADO :: [3f23fd2] API :: 192.168.13.198 - gave correct API KEY. ACCESS GRANTED
2017-10-05 16:14:48 DEBUG    TORNADO :: [3f23fd2] API :: future: {'sort': 'date', 'type': 'missed|today|soon|later'}
2017-10-05 16:14:48 DEBUG    TORNADO :: [3f23fd2] API :: all kwargs: {'sort': 'date', 'cmd': 'future', 'type': 'missed|today|soon|later'}
2017-10-05 16:14:48 DEBUG    TORNADO :: [3f23fd2] API :: all args: ()
2017-10-05 16:14:48 DEBUG    TORNADO :: [3f23fd2] API :: 192.168.13.198 - gave correct API KEY. ACCESS GRANTED
2017-10-05 16:14:41 DEBUG    TORNADO :: [3f23fd2] API :: history: {'limit': '100', 'type': 'downloaded'}
2017-10-05 16:14:41 DEBUG    TORNADO :: [3f23fd2] API :: all kwargs: {'type': 'downloaded', 'cmd': 'history', 'limit': '100'}
2017-10-05 16:14:41 DEBUG    TORNADO :: [3f23fd2] API :: all args: ()
2017-10-05 16:14:41 DEBUG    TORNADO :: [3f23fd2] API :: 192.168.13.198 - gave correct API KEY. ACCESS GRANTED
2017-10-05 16:14:41 DEBUG    TORNADO :: [3f23fd2] API :: future: {'sort': 'date', 'type': 'missed|today|soon|later'}
2017-10-05 16:14:41 DEBUG    TORNADO :: [3f23fd2] API :: all kwargs: {'sort': 'date', 'cmd': 'future', 'type': 'missed|today|soon|later'}
2017-10-05 16:14:41 DEBUG    TORNADO :: [3f23fd2] API :: all args: ()
2017-10-05 16:14:41 DEBUG    TORNADO :: [3f23fd2] API :: 192.168.13.198 - gave correct API KEY. ACCESS GRANTED
2017-10-05 16:14:30 DEBUG    TORNADO :: [3f23fd2] API :: history: {'limit': '100', 'type': 'downloaded'}
2017-10-05 16:14:30 DEBUG    TORNADO :: [3f23fd2] API :: all kwargs: {'type': 'downloaded', 'cmd': 'history', 'limit': '100'}
2017-10-05 16:14:30 DEBUG    TORNADO :: [3f23fd2] API :: all args: ()
2017-10-05 16:14:30 DEBUG    TORNADO :: [3f23fd2] API :: 192.168.13.198 - gave correct API KEY. ACCESS GRANTED
2017-10-05 16:14:30 DEBUG    TORNADO :: [3f23fd2] API :: future: {'sort': 'date', 'type': 'missed|today|soon|later'}
2017-10-05 16:14:30 DEBUG    TORNADO :: [3f23fd2] API :: all kwargs: {'sort': 'date', 'cmd': 'future', 'type': 'missed|today|soon|later'}
2017-10-05 16:14:30 DEBUG    TORNADO :: [3f23fd2] API :: all args: ()
2017-10-05 16:14:30 DEBUG    TORNADO :: [3f23fd2] API :: 192.168.13.198 - gave correct API KEY. ACCESS GRANTED
2017-10-05 16:14:18 DEBUG    SNATCHQUEUE-MANUALSNATCH-316544 :: [3f23fd2] Transaction with 1 queries executed
2017-10-05 16:14:18 DEBUG    SNATCHQUEUE-MANUALSNATCH-316544 :: [3f23fd2] 316544: Formatting pattern: %SN - %Sx%0E - %EN - %QN -> District 31 - 015 - Épisode 15 - 720p WEB-DL
2017-10-05 16:14:18 DEBUG    SNATCHQUEUE-MANUALSNATCH-316544 :: [3f23fd2] Found codec for District 31 Épisode 15
2017-10-05 16:14:18 DEBUG    SNATCHQUEUE-MANUALSNATCH-316544 :: [3f23fd2] Checking if we should stop searching for a better quality for for episode District.31.S02E15.WEBRiP.720p.x264
2017-10-05 16:14:18 INFO     SNATCHQUEUE-MANUALSNATCH-316544 :: [3f23fd2] Saved District.31.S02E15.WEBRiP.720p.x264 to District.31.S02E15.WEBRiP.720p.x264.torrent
2017-10-05 16:14:18 DEBUG    SNATCHQUEUE-MANUALSNATCH-316544 :: [3f23fd2] No parent path provided in District.31.S02E15.WEBRiP.720p.x264.torrent, unable to get permissions from it
2017-10-05 16:14:18 DEBUG    SNATCHQUEUE-MANUALSNATCH-316544 :: [3f23fd2] GET URL: http://192.168.13.198:8086/jackett/dl/ethor/?jackett_apikey=b66if81o0czme93f44ooj49rb0a9ta8a&path=LzJBaGhZSERiT045RXFsU2o0aGJYSjBaV3dNYVFKVUxzVmV1Z0Q5ckhnWmJZNXd2eDdVUEtZUzhTN2Z1SVpUMjgvSmk2eUJ5VTZHWmdvb0d1T2VpREFZSUZLbm9pV3ZDUGg2Nk5oMW03NktpaS9xWmloSkxqZlhWcXNWcytYSEtXTkxBQ2VmMC92bTlZT3VTYk5rWk9YOGhjMjV4Z1NwVGQ5Uld6R0hCOStEZUxlem1iQ1lnMXZEdnArSDVsZUZFZVA3VEd1enhlUExOSTNBSDBVZk1oYTF2WEdrUWxIaVhrZm90UUdtMTUrVUVRM09laVhCcG83c2lvQVYxM0FQYi9Dd0gvRTlvb1l4UHZBVk03T1BHb3ZZOCtrclc3dkpYcUZJblBVMDBHZ1puSmRqMWZxNmtqWnF0ZVo4TFhOdnRZeTEvNDJudWxGa3d5ekpuTnByb3R3PT01&file=District+31+S02E15+WEBRiP+720p+x264.torrent [Status: 200]
2017-10-05 16:14:17 INFO     SNATCHQUEUE-MANUALSNATCH-316544 :: [3f23fd2] Downloading District.31.S02E15.WEBRiP.720p.x264 from Ethor at http://192.168.13.198:8086/jackett/dl/ethor/?jackett_apikey=b66if81o0czme93f44ooj49rb0a9ta8a&path=LzJBaGhZSERiT045RXFsU2o0aGJYSjBaV3dNYVFKVUxzVmV1Z0Q5ckhnWmJZNXd2eDdVUEtZUzhTN2Z1SVpUMjgvSmk2eUJ5VTZHWmdvb0d1T2VpREFZSUZLbm9pV3ZDUGg2Nk5oMW03NktpaS9xWmloSkxqZlhWcXNWcytYSEtXTkxBQ2VmMC92bTlZT3VTYk5rWk9YOGhjMjV4Z1NwVGQ5Uld6R0hCOStEZUxlem1iQ1lnMXZEdnArSDVsZUZFZVA3VEd1enhlUExOSTNBSDBVZk1oYTF2WEdrUWxIaVhrZm90UUdtMTUrVUVRM09laVhCcG83c2lvQVYxM0FQYi9Dd0gvRTlvb1l4UHZBVk03T1BHb3ZZOCtrclc3dkpYcUZJblBVMDBHZ1puSmRqMWZxNmtqWnF0ZVo4TFhOdnRZeTEvNDJudWxGa3d5ekpuTnByb3R3PT01&file=District+31+S02E15+WEBRiP+720p+x264.torrent
2017-10-05 16:14:17 INFO     SNATCHQUEUE-MANUALSNATCH-316544 :: [3f23fd2] Downloading District.31.S02E15.WEBRiP.720p.x264 with 124 seeders and 0 leechers and size 463.77 MB from Ethor
2017-10-05 16:14:17 INFO     SNATCHQUEUE-MANUALSNATCH-316544 :: [3f23fd2] Beginning to manual snatch release: District.31.S02E15.WEBRiP.720p.x264
```

**Comment by saitoh183** [comment]
Seems that if i dont use blackhole and i use rtorrent, it does work, so it is only a problem when using blackhole

**Comment by medariox** [comment]
Do you have the **Black hole folder location** set for **NZB Search**?
![img](https://i.imgur.com/e49pwBd.png)

**Comment by saitoh183** [comment]
No only in torrent? Do I need to set it in NZB also? Since it says for  NZB files I figured I didn't. Also I never did that in sickrage.

**Comment by medariox** [comment]
It's a workaround. If you confirm that's the issue it will be fixed properly ASAP.

**Comment by medariox** [comment]
@saitoh183 Did it solve the issue?

**Comment by saitoh183** [comment]
@medariox yes adding the path to the nzb blackhole works. This is a good workaround if you dont use nzb but if you do, this is a problem

**Comment by medariox** [comment]
Fixed in develop with https://github.com/pymedusa/Medusa/pull/3153

**Comment by saitoh183** [comment]
@medariox and @fernandog 

The Issue still seems unresolved


Branch: develop
Commit: 364be02d86ea2ae3f887081d4ce23856384efbb9
Version: v0.1.17
Database: 44.8
--

When i try a manual grab of a file i end up getting a nzb file that is dropped in the location that is set under NZB Search (if you set nothing, it is the config folder of medusa)
Logs (Manual and Daily search):
```
2017-11-22 02:10:40 INFO     SNATCHQUEUE-MANUALSNATCH-265625 :: [364be02] Saved Memoires.Vives.S05E22.WEBRiP.720p.x264 to /mnt/Downloads/Seedbox/send/ftvshows/Memoires.Vives.S05E22.WEBRiP.720p.x264.nzb
2017-11-22 02:10:39 INFO     SNATCHQUEUE-MANUALSNATCH-265625 :: [364be02] Downloading Memoires.Vives.S05E22.WEBRiP.720p.x264 from ETHOR at http://192.168.13.198:8086/jackett/dl/ethor/?jackett_apikey=**********&path=bWtnTURVT0h6OXNqUjlyb0RiK0MyMUwrdndLMVlpdzFibjBVTUI5b3pQL0VwMkErU1p1WU5WZHdSVTk3U0lNY0VOSkUrYXR4MnVGTTFscWpmWTdyTHhwbUR1a3hmUVNJUmJtM0IweFBoYnFKWWc3aEs4YkFjdllmM3hERlhobzBsZ0FPZXJQVFlHUWZubFA1SWJldmh2V1lOcTdBNnlMWTM5VlRlZ3MwR1lvcHZ0eWJrdVExRUJyMlZZVXJWSVh3eEVuRGk3S0lJZEVlMjI1VDZLaXJyNmI0QnY2VVd5UW53aWRQU0o5U1pUbkkrQzJneHpGbWJIUnphOFltemxlbzhCbndoWEFjbklOU05iUjlkcVpDWHVKYjJnM1Y3WEFjbmI0Q285a3c5ZnZaSDJCQko3WU1FUEVieis0Y1c5T3pWamVyQzVFZk5QOW5uZXNPc1RYYkRRPT01&file=Memoires+Vives+S05E22+WEBRiP+720p+x264
2017-11-22 02:10:39 INFO     SNATCHQUEUE-MANUALSNATCH-265625 :: [364be02] Downloading Memoires.Vives.S05E22.WEBRiP.720p.x264 with 21 seeders and 0 leechers and size 960.48 MB from ETHOR
2017-11-22 02:10:39 INFO     SNATCHQUEUE-MANUALSNATCH-265625 :: [364be02] Beginning to manual snatch release: Memoires.Vives.S05E22.WEBRiP.720p.x264
```
```
2017-11-22 00:17:46 INFO     SEARCHQUEUE-DAILY-SEARCH :: [364be02] Saved Unité.9.-.S06E11.20171121.-.720p.HDTV.x264-Handy to /mnt/Downloads/Seedbox/send/ftvshows/Unité.9.-.S06E11.20171121.-.720p.HDTV.x264-Handy.nzb
2017-11-22 00:17:45 INFO     SEARCHQUEUE-DAILY-SEARCH :: [364be02] Downloading Unité.9.-.S06E11.20171121.-.720p.HDTV.x264-Handy from ETHOR at http://192.168.13.198:8086/jackett/dl/ethor/?jackett_apikey=**********&path=bTlKdnpGMW1pcFNzQlNQM01XK3VmM2VNb2gySXVNMlhDTzFLWmhiVmJUMzBoS3pLcnhwMmMyWS9WSGhwTkhtUlFNME8zays2eHM1RXE0bFpSMy9mcFpuMG9KQmJKcTJRMFJ6eC83WXJwQ3lNNVlzUjh1SHBoU2YxdEdNZlU0eHIxRjNaM0R5NnRTaVoyUnZ4VVNtVHJkaEVMUG5jOXNiUnNKM2IySGx6YUdZM2JwdGh2OXFhTU41WnJtVjdWeC9Mdmw4cWdidnFacTdyeUQ3cGlJTEpLUWNjbVRycjh1YzFyaU1ZbWh1Q0lQTlozR29BcUJLTWs0dU1ROVpZM3hyNEsvcVhEUmp0ZVQxWHJKVm9IZjQvV3V6SHF3M3FVSEVVTEM2Y2NwVng1YlV3anRsZ01DVWF6dkdQdlRDTFdwWUc2OTZGZmc0Z0d4Y2hPWEJEbE5SVjdnPT01&file=Unité+9+-+S06E11+20171121+-+720p+HDTV+x264-Handy
2017-11-22 00:17:45 INFO     SEARCHQUEUE-DAILY-SEARCH :: [364be02] Downloading Unité.9.-.S06E11.20171121.-.720p.HDTV.x264-Handy with 29 seeders and 7 leechers and size 1013.76 MB from ETHOR
2017-11-22 00:17:44 INFO     SEARCHQUEUE-DAILY-SEARCH :: [ETHOR] :: [364be02] Quality of Unité.9.-.S06E11.20171121.-.720p.HDTV.x264-Handy is 720p HDTV
```
Note that in torrent Search im now using Deluge and not blackhole

**Comment by medariox** [comment]
File is missing the `.torrent` extension for some reason (compare it to the first logs you posted). Seems more like an issue with Jackett.

**Comment by Kilay** [comment]
I still have the issue, file are downloaded with .nzb extension instead of .torrent
I don't think it Jackett issue because if we copy/paste the the url used by Medusa to download the file, we do have the .torrent extension.

```
Branch: master
Commit: ca2c5c4c92888f2f588c74c6770cfa12c6db7f40
Version: v0.1.19
```
```
2017-12-04 09:43:50 INFO     SNATCHQUEUE-MANUALSNATCH-260449 :: [ca2c5c4] Saved Vikings.S05E01.French.Web-DL.720p.AAC-SiR to /volume1/Downloads/complet/Vikings.S05E01.French.Web-DL.720p.AAC-SiR.nzb
2017-12-04 09:43:50 DEBUG    SNATCHQUEUE-MANUALSNATCH-260449 :: [ca2c5c4] User-Agent: Medusa/0.1.17 (Linux; 2.6.32.12; d0095bf5-d8c6-11e7-b6d9-001132190901)
2017-12-04 09:43:50 DEBUG    SNATCHQUEUE-MANUALSNATCH-260449 :: [ca2c5c4] GET URL: http://localhost:5225/dl/yggtorrent/?jackett_apikey=**********&path=bGxkTlNHWHBMQnFIcUJ0cEFrQU1rbG5rL2ZPOUZWYzhyc0tkZ3lhODBUakRacmkraVg1UUtKSERtMmFNZUxrcGVkYzZSUHRLWkpkNzA5RmIrVlgwYi9tN1RZaWEwVDhoS3BTT09ZaU5sL285NFVGck5SM3hZMGdZeXIvRktLeUhjdjQvQnBrcGhiRVpjUytYVnI1WVV0b1pYQkVvTzRGcjRROUprUkFvaWpybFBvU1dIVEJnWGJpMGJ1YkRKTHV2ZXZ0cThDZzFjQVc2YWJYcWswSC9zYVAraDRtcFFGd2dYNXFPbzF3WWpRaWlzRnNCVTRwZEdSWkNzd0FZVUpPVmdYakVGcExUUlBTNjJJa09oRGU5ckRSVUJWTUJSTUtOUXU4d25ySWpnVkJtMWxpOFFDRUpMWFRaeHJJeVN5aHQ4UFNuc1FqUWlDbnk0WTdNSWRDc01KVERETFdOelVGZTdnZVRZdWFKNllJPQ2&file=Vikings+S05E01+French+Web-DL+720p+AAC-SiR [Status: 200]
2017-12-04 09:43:49 INFO     SNATCHQUEUE-MANUALSNATCH-260449 :: [ca2c5c4] Downloading Vikings.S05E01.French.Web-DL.720p.AAC-SiR from YGGTORRENT_JACKETT at http://localhost:5225/dl/yggtorrent/?jackett_apikey=**********&path=bGxkTlNHWHBMQnFIcUJ0cEFrQU1rbG5rL2ZPOUZWYzhyc0tkZ3lhODBUakRacmkraVg1UUtKSERtMmFNZUxrcGVkYzZSUHRLWkpkNzA5RmIrVlgwYi9tN1RZaWEwVDhoS3BTT09ZaU5sL285NFVGck5SM3hZMGdZeXIvRktLeUhjdjQvQnBrcGhiRVpjUytYVnI1WVV0b1pYQkVvTzRGcjRROUprUkFvaWpybFBvU1dIVEJnWGJpMGJ1YkRKTHV2ZXZ0cThDZzFjQVc2YWJYcWswSC9zYVAraDRtcFFGd2dYNXFPbzF3WWpRaWlzRnNCVTRwZEdSWkNzd0FZVUpPVmdYakVGcExUUlBTNjJJa09oRGU5ckRSVUJWTUJSTUtOUXU4d25ySWpnVkJtMWxpOFFDRUpMWFRaeHJJeVN5aHQ4UFNuc1FqUWlDbnk0WTdNSWRDc01KVERETFdOelVGZTdnZVRZdWFKNllJPQ2&file=Vikings+S05E01+French+Web-DL+720p+AAC-SiR
2017-12-04 09:43:49 INFO     SNATCHQUEUE-MANUALSNATCH-260449 :: [ca2c5c4] Downloading Vikings.S05E01.French.Web-DL.720p.AAC-SiR with 123 seeders and 31 leechers and size 735.35 MB from YGGTORRENT_JACKETT
2017-12-04 09:43:49 INFO     SNATCHQUEUE-MANUALSNATCH-260449 :: [ca2c5c4] Beginning to manual snatch release: Vikings.S05E01.French.Web-DL.720p.AAC-SiR
```

**Comment by medariox** [comment]
@Kilay 
Fix is not in master yet.

**Comment by Kilay** [comment]
Oh sorry, my bad. Thank you, I'll wait the release to master branch.
