### ISSUE TITLE
Possible to add and download WWE shows?

### ISSUE THREAD

**Issue by stayupthetree** [pymedusa/Medusa#3708]
Other apps only used the TVDB which didn't give any new information for WWE/UFC stuff. TVMaze does however. Is it possible to do this? I added it successfully but get no results when trying to download or search manually.

**Comment by ripper1967** [comment]
What one you searching for?

**Comment by p0psicles** [comment]
Best bet for now is testing release names, and hoping they get parsed correctly by guessit, through the daily search.

Beside that its a know issue that it's hard to search for them. We have some ideas to fix this, but the combination of it taking allot of effort with little gain.

**Comment by stayupthetree** [comment]
@ripper1967 Both of those would be great. I was ecstatic when it pulled all the info properly. The shows are on the NZBIndexers, so right now I use RSS. I have just had this dream for years of it being automatic.

**Comment by p0psicles** [comment]
Im working on a feature where you can configure your own search strings. You might wanna took a look at that branch. Ill have it working in a couple of weeks.

**Comment by medariox** [comment]
Try setting the show as air by date?

**Comment by stayupthetree** [comment]
Maybe I am explaining it wrong. Medusa finds it, sends it to NZBGet, NZBGet downloads it, then I get stuck on Post Processing. Show is set to Sports

**Comment by medariox** [comment]
Thanks for the bug report. This is now fixed with https://github.com/pymedusa/Medusa/pull/4294 and it will be available with the next release.

**Comment by bourgouinadrien** [comment]
Hi here.
Seems to be fixed but still not working for me.
I added WWE Smackdown as Format > Sports and it's still looking for things like "WWE SmackDown - S21E52 - Friday Night SmackDown 1062"
Feature request seems to not been finish 
https://github.com/pymedusa/Medusa/labels/Feature%20request

What about it ?
How can I get it as my torrent are like "WWE.SmackDown.DD.MM.YYYY.FRENCH.720p.HDTV.x264-COLL3CTiF"

Thank.

**Comment by medariox** [comment]
Try with air by date sitting for that naming.

**Comment by p0psicles** [comment]
Run a search and check your debug logs. Can't imagine that it's using that format
