### ISSUE TITLE
Edit anime show hangs

### ISSUE THREAD

**Issue by h3llrais3r** [pymedusa/Medusa#5312]
**Describe the bug**
When trying to edit an anime show, the application hangs.
Only solution is restart it.
Editing a normal show doesn't seem to have the problem.

**Screenshots**

![image](https://user-images.githubusercontent.com/1945295/46090348-d793e980-c1b0-11e8-9419-94344d306dbc.png)

**Medusa (please complete the following information):**

- OS: Windows-8-6.2.9200
- Branch: master
- Commit: 4614efc
- Version: v0.2.10
- Database: 44.12

**Logs:**
```
<-- Please replace this whole line with your logs -->
```
</details>

**Comment by p0psicles** [comment]
Should be fixed now in develop. Could you test that?

**Comment by h3llrais3r** [comment]
I just tried with the latest develop version but I'm still having the issue.
Page hangs forever.

I have my chrome dev tools open and I got the following exception during loading of the editshow page:

![image](https://user-images.githubusercontent.com/1945295/46127876-41080c80-c232-11e8-9baa-8d9092e0f0d5.png)

which finally results in

**Comment by p0psicles** [comment]
Ow seems to be something with the client. Can you try a different machine/client? Maybe firefox?

**Comment by p0psicles** [comment]
can you test the referenced branch?

**Comment by h3llrais3r** [comment]
Will test this evening and let you know the outcome.

**Comment by h3llrais3r** [comment]
Fixed with PR :+1:
