### ISSUE TITLE
After upgrading from sickrage using domain name to connect doesn't work..

### ISSUE THREAD

**Issue by plato79** [pymedusa/Medusa#5419]
I was using sickrage for a longtime on port 8081.. A few days ago there was again(!) some confusion about who owns sickrage... So I finally grew tired of it and switched to Medusa..  I put my  sickbeard.db and config.ini to Medusa folder and started it. Medusa built its' own main.db and modified config.ini.. Everything seemed to be ok..

But one thing didn't work. I'm using nginx to forward a domain name to 127.0.0.1:8081 port. It was working without any problem with sickrage. It allowed HTTPS connection with SSL certificate from Letsencrypt etc..

But now with domain it only shows this without any theme ( no black background, completely in Times New Roman, with Left aligned):

Loading…
If this is taking too long,
click here to show the page.

Clicking "here" doesn't change anything.

If I can see that message it means domain forwarding still works but somehow I cannot see any content other than loading screen..

When I use the port 8081 to connect, there is no problem though.. It opens up the web ui..

I tried different browsers on different computers to assure that it wasn't about cache. It was a first time load of the site on the computers so I'm sure it's not about cache. So, what could be the culprit?

**Comment by medariox** [comment]
Already had a look at https://github.com/pymedusa/Medusa/wiki/Reverse-Proxy-setup ?

**Comment by plato79** [comment]
My configuration is like this.. ssl-params.conf file has the ssl information bit in it.

I'm using this configuration for every sub-domain and it was working with sickrage and still working with deluge, freenas web ui, Couchpotato etc..

```
  server {
    listen 443 ssl;
    server_name my.domain.com;
    include ssl-params.conf;
    location / {
      proxy_pass http://127.0.0.1:8081/;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_read_timeout 43200000;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $http_host;
      proxy_set_header X-NginX-Proxy true;
    }
      
  }
```

**Comment by OmgImAlexis** [comment]
Maybe try following the setup [here](https://github.com/pymedusa/Medusa/wiki/Reverse-Proxy-setup#nginx) and see if it helps, there are a few headers you're missing vs what we recommend. It could be you're missing one of the ones we need.

**Comment by plato79** [comment]
It seems you are correct.. After commenting my code and using the code from setup, it works. What could be the required ones thought? I was using http_host instead of host.. Is this the reason? Or the parameters with 443 ports?

**Comment by plato79** [comment]
Sorry, accidentally closed. The problem is resolved but I would like to know what could be the cause.

**Comment by bonebox** [comment]
I have the exact same problem.  Just switched from SickRage which worked fine. Updating with the  nginx config from https://github.com/pymedusa/Medusa/wiki/Reverse-Proxy-setup doesn't fix it after reloading. I am using webroot, which it appears that config doesn't include.

**Comment by OmgImAlexis** [comment]
Just wonder, do either of you have the x header setting enabled in medusa?

**Comment by plato79** [comment]
I don't have them enabled.. Though unlike @bonebox , using reverse proxy setup worked for me..

**Comment by p0psicles** [comment]
I don't think that setting is needed.
I always had it enabled. But works just as fine disabled.
I'm using nginx + reverse proxy with letsencrypt cert on it -> `http://localhost:8081/medusa`

**Comment by bonebox** [comment]
Where is the x header setting located? There's nothing with "header" in my `config.ini`.  Would either @plato79 or @p0psicles mind posting the relevant parts of their `server.ReverseProxy.conf` so I can see if I may have missed something?

**Comment by bonebox** [comment]
I got it working. Appears that it was an issue with my SSL certs.

**Comment by plato79** [comment]
The configuration is in General->Interface->Reverse proxy header..

Though it seems this option is not required. Anyway, I'm closing this issue, because it's solved for everyone.
