### ISSUE TITLE
Timeout of 10000ms exceeded when loading very large show

### ISSUE THREAD

**Issue by Undeadllama** [pymedusa/Medusa#5531]
**Describe the bug**
All shows tested so far load fine with the exception of "BBC Documentaries".
When attempting to view in the web interface it will sit there loading for a good while, probably around a minute, and then eventually just display a blank page with "Loading..." in the top left and the standard page footer containing stats:

![medusa_bbcdocs](https://user-images.githubusercontent.com/3908975/47614700-b9fdbc80-da9b-11e8-895f-5bfc6f07e49f.JPG)

This appears to be specific to Chrome but even on other browsers I receive timeout errors when attempting to save/make changes within the show page.

It looks to me like there are simply too many episodes listed under this show for Medusa or the browser to cope in a reasonable timeframe (there are thousands).

Enabling debug logging in Medusa does not appear to produce anything useful in the logs for Web GUI interactions, but I will reproduce and upload if required.

**To Reproduce**
1. Add the show "BBC Documentaries" to Medusa.
2. After it has finished adding attempt to browse to the show and view the list of episodes using Chrome browser.

**Expected behavior**
Timeouts are obviously always a balancing act and given the quantity of episodes in the show it's not surprising the timeout is being hit.
The question is, can anything be done to process the data faster or is the only way to resolve this to extend the timeout?
If extending the timeout is the only way, is this something I can adjust or would it need to be changed in the Medusa code?

**Screenshots**
https://i.imgur.com/PDK2gbL.jpg

**Medusa (please complete the following information):**
 - OS: Windows Server 2012 R2
 - Branch: master
 - Commit: 4614efc77151ded92ef458a09dec39f8bd5acfc6 

**Logs:**
Chome developer console output:
<details>

```
createError.js:16 Uncaught (in promise) Error: timeout of 10000ms exceeded
    at t.exports (createError.js:16)
    at XMLHttpRequest.d.ontimeout (xhr.js:95)
t.exports @ createError.js:16
d.ontimeout @ xhr.js:95
Promise.then (async)
getShows @ shows.js:91
(anonymous) @ vuex.esm.js:704
u.dispatch @ vuex.esm.js:426
dispatch @ vuex.esm.js:332
created @ displayShow?indexername=tvdb&seriesid=79660:206975
Se @ vue.esm.js:2921
t._init @ vue.esm.js:4630
dn @ vue.esm.js:4729
(anonymous) @ displayShow?indexername=tvdb&seriesid=79660:206962

```
</details>

**Comment by medariox** [comment]
We have bumped the timeout to 30000s in develop, so this should be fixed with the next release.

**Comment by Undeadllama** [comment]
Awesome, thanks for the very quick reply!

**Comment by PC001** [comment]
I'm still having this issue now. Did this timeout bump ever make it into master?

Thanks!

**Comment by p0psicles** [comment]
Not sure. But we're working on a proper fix

**Comment by XxUnkn0wnxX** [comment]
this is very frustrating, my libbary is masisve & i run into these non-stop it usualy takes like 8-26 atemts before is succeedes.

![Screen Shot 2020-01-07 at 4 43 47 pm](https://user-images.githubusercontent.com/2242880/71871445-4eb67c80-316d-11ea-9995-a739f7cab3d0.jpg)

i'm on develop branch: 1eadfaf1bad602f96efe411d2a34f23482911286

is there a way i can edit this as a test to like 3 min or more for the timmer? & if possible maybe add in an option in config to manually assign the limits.

**Comment by p0psicles** [comment]
What are your system specs?

**Comment by p0psicles** [comment]
How do you have postprocessing set up?

**Comment by p0psicles** [comment]
Pause old ended shows as much as possible

**Comment by XxUnkn0wnxX** [comment]
![Screen Shot 2020-01-08 at 12 43 19 am](https://user-images.githubusercontent.com/2242880/71899461-e50b9200-31af-11ea-96ac-9dbdb46b3e27.jpg)
Full Report: 
[XxUnkn0wnxX iMac 2020-01-08.pdf](https://github.com/pymedusa/Medusa/files/4030925/XxUnkn0wnxX.iMac.2020-01-08.pdf) - ignore the heavy ram usage warning in this case, i usualy have around 16 gigs or more out of my 32gig. chrome was eating up for some reason atm)


Post Processing
1: Scheduled Post-Processing going off every 10 mins for my ManualDL folder for anything i put there
2: SabNZB uses https://github.com/clinton-hall/nzbToMedia 
[autoProcessMedia 2cfg.zip](https://github.com/pymedusa/Medusa/files/4030908/autoProcessMedia.2cfg.zip) i removed any senstative info. i use Medusa's API setup via the script.
i have failed download handling setup.
qBittorent i have it using nzbtomedia as well.

**Comment by p0psicles** [comment]
You can temp disable the 10 min postprocessing. Restart Medusa. And see if that fixes things.

**Comment by XxUnkn0wnxX** [comment]
its somewhat more resposive but i still feel there is a delay there.

**Comment by medariox** [comment]
@XxUnkn0wnxX 
Saving a show already runs in a separate thread, so it shouldn't matter much what is going on in the background. Can you share the browser network logs that show the slowdown? Including the related Medusa logs. I think that could help to narrow down the issue.

**Comment by XxUnkn0wnxX** [comment]
well i cannot seem to get it to timeout atm.. but i will save the network logs as well as medusa log when it starts to hang on me again. as it tends to happen when either doing a lot of backlogging or before/after post-processing episodes & at the same time i try edit & save a show. and then from there no matter how many times i restart medusa it hangs for sevral hours till it fixes it self... but it tends to come & go often..

**Comment by p0psicles** [comment]
You should check what's running at that time. Like is it also continually running daily searches? What's the CPU usage?

**Comment by XxUnkn0wnxX** [comment]
ok it happend again, Medusa was also very slugish pages loading slow, config took like over 2 seconds to load values from file before they displayed on the page.

here is the network capture of the failed attemts till it succeeded to save.
as well as the main log file.

[Medusa Log.zip](https://github.com/pymedusa/Medusa/files/4080831/Medusa.Log.zip)

Proper Finder
& Backlog where runnng.

CPU usage was low very minimum even when its doing a lot Medusa never spikes my usage. the only thing that spikes it is when decoding x265 video.

**Comment by XxUnkn0wnxX** [comment]
@medariox @p0psicles this is still happening, 

![Screen Shot 2020-01-28 at 5 10 28 am](https://user-images.githubusercontent.com/2242880/73201475-31ce0180-418d-11ea-8367-a70d66df380c.jpg)

[Medusa Log (26-01-2020).zip](https://github.com/pymedusa/Medusa/files/4118652/Medusa.Log.26-01-2020.zip)

Nothing was active in the server status screen & yet i cannot save these shows.

on latest dev commit: 6a0cd6875ca3e31344a674f9b92b88070c1a8618
