### ISSUE TITLE
NZBGeek provider api key not saved

### ISSUE THREAD

**Issue by Zw3rv3r** [pymedusa/Medusa#5601]
In "Search Providers" tab "Provider Options" you can enter an API key for "Configure provider" NZBGeek in a "API key" password input field. This API key is not saved. The provider doesn't work because of a missing API key.

**To Reproduce**
1. Go to "Search Providers" tab "Provider Options"
2. In select box "Configure Provider" select option "NZBGeek". Input fields specific for this provider should appear.
3. In **password** input field "API Key" enter your NZBGeek API key.
4. Press the "Save Changes" button. A "Loading" message should appear and you will be redirected to the "Provider Priorities" tab.
5. Go to the tab "Provider Options"
6.  In select box "Configure Provider" select option "NZBGeek". Input fields specific for this provider should appear.
7. In **password** input field "API Key" is empty. It is not saved in config.ini (key: nzbgeek_api_key) either.

**Expected behavior**
After pressing the "Save Changes" button and navigation to the "Provider Options" tab I should be able to verify my API key in a **text** input field. Also, the API key should probably be stored in the config.ini file.

**Medusa (please complete the following information):**
 - OS: Ubuntu 18.04 LTS running latest Docker with latest linuxserver/medusa container
 - Branch: master
 - Commit: 0c0a73583452f988c518adeafa75ee1f17987bdf

**Comment by medariox** [comment]
This should be fixed with the new version, please reply if it's not the case.

**Comment by dadadom** [comment]
Still not working. It seems that the mapping from field id to the corresponding configuration key is wrong.

**Comment by kjelderg** [comment]
I am seeing the same in d9c31da

**Comment by p0psicles** [comment]
Any errors/warnings in your browser when you try to save?
Does the config.ini file change when you save?
Any other logs? Pls enable debug logs, and restart.
What's your browser version?
You used the newznab tab to configure?

**Comment by kjelderg** [comment]
It seems to have been a fluke for me.  When I restarted the service to enable debug logs, saving the api key worked fine.
