### ISSUE TITLE
[develop] Server status shows all False

### ISSUE THREAD

**Issue by Yellow1144** [pymedusa/Medusa#5951]
Server status under alive column shows all red False. Under the Active column, only two of the schedulers show as True. Despite this, Medusa seems to be working properly. Manual downloads are post processing, shows are being downloaded and post processed properly as are propers.

Branch: develop 
Commit: efeec893f8d3ddc3dc9650b60a4a6aa7cd7541a9 
Version: v0.2.14 
Database: 44.13
Python Version: | 3.5.2 (default, Nov 12 2018, 13:43:14) [GCC 5.4.0 20160609]
SSL Version: | OpenSSL 1.0.2g 1 Mar 2016
OS: | Linux-4.15.0-33-generic-x86_64-with-LinuxMint-18.3-sylvia Locale: | en_CA.UTF-8

There are no errors in the logs. Mine is a very busy system. A new 12MB log file can be generated up to every 4 minutes. I am logging in debug mode and have a large library and show list.

**Comment by p0psicles** [comment]
Yeah we noticed this. And can't really find the root cause.
Seems to be limited to Linux installations. 
All rasp pi installations also seems to be affected.

**Comment by Yellow1144** [comment]
Glad you're aware of it.

**Comment by p0psicles** [comment]
It's related to the python 3 changes in develop. But all the threads are running fine. So it's just a reporting bug. Not that important. We'll fix it before it's merged into master.

**Comment by p0psicles** [comment]
@labrys If you feel bored. Know anything that could help us? Seems like the is_alive() property in threading.thread is always false on some Linux installations with py3. I can't reproduce on development installs. Also tried an Ubuntu on a vm.

**Comment by labrys** [comment]
Sorry for the delay in responding.  

To my knowledge the `thread.is_alive()` property is pretty much guaranteed on all platforms in all recent versions of python.  

More likely is improper usage of a thread that didn't exhibit the error on previous versions.  My immediate guess, since this problem is related to linux only, is that its related to running as a daemon since Windows doesn't daemonize.

**Comment by p0psicles** [comment]
Ok I can test that. Tnx..

**Comment by p0psicles** [comment]
I tested running medusa from command line with and without the `--daemon` parameter.
Without the daemon param it works fine, with the param it's having problems referring to the correct Thread object.

I even tried creating a "simplified" is_alive method.
```
    def is_alive(self):
        if six.PY3:
            return self._initialized and not self._is_stopped
        return self._Thread__initialized and not self._Thread__stopped
```
But that's having the same issue. So when calling `self._initialized and not self._is_stopped` on linux where medusa is started daemonized with python3, the error occurs.

**Comment by p0psicles** [comment]
It's also giving some strange unexpected behavior when I utilize my is_alive method on linux with python 2 with and without daemonize.

**Comment by labrys** [comment]
To be honest the daemonizing of the threads should be removed.  It's not implemented correctly and likely isn't what Medusa should be doing anyway since you want proper cleanup upon termination.

Note from Python docs:

> Note Daemon threads are abruptly stopped at shutdown. Their resources (such as open files, database transactions, etc.) may not be released properly. If you want your threads to stop gracefully, make them non-daemonic and use a suitable signalling mechanism such as an Event.

**Comment by p0psicles** [comment]
Ok I'll replace them with stop Events. Ill alse try to improve Medusa demonization code maybe that makes a difference.
Tnx

**Comment by p0psicles** [comment]
I checked we don't daemonize our threads. We only have the ability to run the main process as a daemon.
So i'll be focussing on that.

**Comment by medariox** [comment]
Using the new systemd should fix this: https://github.com/pymedusa/Medusa/blob/develop/runscripts/init.systemd

**Comment by Yellow1144** [comment]
Having a look at that, that file has Medusa running under python 2.7. I know you are moving Medusa over to python 3 and on my system, using python 3.5 and now 3.7, I still see this problem.

Branch: develop 
Commit: fd60a6ea5a149a7f89f78a23f828bcb8315e1483 
Version: 0.3.0 
Database: 44.14
--
Python Version: | 3.7.2 (default, Jan 11 2019, 21:31:15) [GCC 5.4.0 20160609]
SSL Version: | OpenSSL 1.0.2g 1 Mar 2016
OS: | Linux-4.15.0-45-generic-x86_64-with-LinuxMint-18.3-sylvia
Locale: | en_CA.UTF-8

**Comment by medariox** [comment]
Using the new systemd should fix this: https://github.com/pymedusa/Medusa/blob/develop/runscripts/init.systemd

**Comment by p0psicles** [comment]
I had the same issue. Fixing the systemd nit script fixed the issue

**Comment by Yellow1144** [comment]
Sorry, deleted my most recent post. Actually read the systemd file. Removed --daemon from my startup options using python 3.7 and it works now.. 
Going back to sleep..
Thank you!
