### ISSUE TITLE
Casting to int failed error after upgrade to 0.3.0

### ISSUE THREAD

**Issue by adix** [pymedusa/Medusa#6408]
**Describe the bug**
I have been getting a heap of these errors since upgrading to version 0.3.0 and still with 0.3.1
A whole pile of them appear at the same time, every few days.
Medusa still seems to be running without noticeable issue...possibly something is not working correctly in the background that I haven't detected yet.

![Error Log](https://user-images.githubusercontent.com/43101445/54860256-7eb5a000-4d52-11e9-89a6-b5d913b140ef.jpg)
![Medusa Info](https://user-images.githubusercontent.com/43101445/54860258-86754480-4d52-11e9-8257-76bf0994177f.jpg)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Medusa (please complete the following information):**
 - OS: [e.g. ubuntu 14.04 x64]
 - Branch: [e.g. master, develop]
 - Commit: [e.g. c65ca2]

**Logs:**
<details>

```
<-- Please replace this whole line with your logs -->
```
</details>

**Additional context**

**Comment by p0psicles** [comment]
Pls enable debug logs restart and reproduce. Post logs at time of error

**Comment by adix** [comment]
Log file attached after enabling debug logs and error reproduced at 2019-03-24 15:13:57
[application.log](https://github.com/pymedusa/Medusa/files/3000220/application.log)

**Comment by medariox** [comment]
Is your DB coming from SR? Try removing the show `This Is Us` (keep the files) and adding it again. It should fix the issue.

**Comment by adix** [comment]
Yes, I moved from SR to Medusa about 5 months ago...that show was already in the DB at the time.  Will try re-adding the show and let you know how it goes.  Thanks for the help.

**Comment by adix** [comment]
After removing the show `This Is Us` and adding it back into Medusa again I am still getting the same error.  Is there anything associated with the upgrade to version 0.3.0 that would have triggered this as I wasn't seeing these errors previously?

If it is SR database related, can I edit the database to fix this without having to add all my shows again?

**Comment by medariox** [comment]
Upload you DB to https://send.firefox.com and I'll see what I can do.

**Comment by adix** [comment]
Uploaded DB here:
https://send.firefox.com/download/54f0353bdbc2a72c/#MLSvXl-1rxdufUkVygAzig

**Comment by medariox** [comment]
@adix 
Here you go: https://send.firefox.com/download/9e271122dd4d600c/#e6wGTcAUkK8-cGQQwx_GkA
SR inserted some funny values in your DB, I've replaced them with the correct ones.

**Comment by adix** [comment]
Thanks for your help.  I will let you know how Medusa runs with the updated DB.

**Comment by medariox** [comment]
Closing as fixed for now.
