### ISSUE TITLE
Shows List, Tabs & Search won't show or work

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [pymedusa/Medusa#7428]
**Describe the bug**
Tabs wont show or work most of the time (marked in yellow)
& search never shows when tabs are broken in this state.

**To Reproduce**
update to commit: b03055acefa289fd49c4a504241981f4af42f22d
open any browser chrome/firefox private mode or not & go to shows list/home page
& most of the time the tabs won't work.
keep refreshing page till it breaks or fixes itself but most of the time its broken.

**Screenshots**
Chrome
![Screen Shot 2019-11-29 at 12 32 31 pm](https://user-images.githubusercontent.com/2242880/69838137-551c2380-12a6-11ea-9a14-3cda2722d0b8.jpg)

Firefox
![Screen Shot 2019-11-29 at 12 34 01 pm](https://user-images.githubusercontent.com/2242880/69838150-5f3e2200-12a6-11ea-9d01-1a0cd1e21a76.jpg)

**Medusa (please complete the following information):**
 - OS: macOS Catalina, 10.15.1
 - Branch: develop
 - Commit: b03055acefa289fd49c4a504241981f4af42f22d
 - Python version: 3.7.5
 - Database version: 44.14

**Debug logs (at least 50 lines):**
<details>
All Logs: https://github.com/pymedusa/Medusa/files/3903391/Logs.zip

Most Recent: https://gist.github.com/XxUnkn0wnxX/44c0d275a30ee8d562a9dc4ac62b5966
</details>

**Additional context**
master has no issues, these past few commits in developer have been getting worse & worse i thought it was temporarily after the 1st 2-6 refreshes it fixed itself but it seems to be more permanent now.

@pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
Master also has the issue. I've also noticed it for a couple of months now. Will fix it when vueifying home.

**Comment by XxUnkn0wnxX** [comment]
as shown in the image, this now always displays like this for me in develop even with the latest commit: 64088438fe4dfea0fe131ec04be001d68c0aec58

no amount of cache clears, or temp fixes work. all browsers, Chrome, MS Edge, Firefox, Safari all display like this 100% of the time now.

**Comment by p0psicles** [comment]
Ooh the tabs. Yeah om working on it here. Will be fixed when this is merged. https://github.com/pymedusa/Medusa/pull/5345

**Comment by XxUnkn0wnxX** [comment]
@p0psicles 
as of commit 8b7f433d4dce89058a8b9b62cc9bcd7a162a3344 to master frontend tabs is now perma broken, search also no longer works.

i ran some tests the las working commit where home was like this:
![Screen Shot 2019-12-09 at 8 38 13 pm](https://user-images.githubusercontent.com/2242880/70424687-e0c25b00-1ac3-11ea-9e73-2f4649b2ff8d.jpg)
was: 90f59e47ddcae341d9af0560b2588ea775902735

from 198f5bf8ee9b665534e287d755974a239b0f15fc & onwards its like this forever:
![Screen Shot 2019-12-09 at 8 42 25 pm](https://user-images.githubusercontent.com/2242880/70424996-6fcf7300-1ac4-11ea-8e44-9ed060db422d.jpg)

i know there is an upcoming fix for it, but isn't there anything that can be done now? or workaround fix? master being the stable build should not be in this state its frustrating...

**Comment by medariox** [comment]
Should be fixed with https://github.com/pymedusa/Medusa/pull/7478

**Comment by XxUnkn0wnxX** [comment]
@medariox not fixed, this even happens on my phone:

![IMG_1909](https://user-images.githubusercontent.com/2242880/70736401-5b110a80-1d64-11ea-90ac-f7ba93fdb593.png)

**Comment by medariox** [comment]
I wrote that it _should_ be fixed. You will have to wait for the next release.

**Comment by p0psicles** [comment]
I tried to do a quick fix. Better to just disable tabs for now. And reenable when we merge the new home page.

**Comment by XxUnkn0wnxX** [comment]
but search doesnt even work either... when you hover over the top pr the bar

**Comment by p0psicles** [comment]
it's in config - Anime - look & feel.

Also it's working correct for me now.
Maybe your missing some posters? That it's timing out on loading them?
Are you running medusa on a very slow spec/machine?

running develop:
![image](https://user-images.githubusercontent.com/1331394/70851751-89dccd00-1e99-11ea-8399-b264ce8cbae1.png)

**Comment by p0psicles** [comment]
Last attempt for now.
#7488  I'll merge that into dev.
Can you test it after merge?

**Comment by XxUnkn0wnxX** [comment]
well here is a full profile report of my machine:
[XxUnkn0wnxX iMac 2019-12-15.pdf](https://github.com/pymedusa/Medusa/files/3964147/XxUnkn0wnxX.iMac.2019-12-15.pdf)

**Comment by XxUnkn0wnxX** [comment]
@p0psicles so switched to the feature/small-ui-fixes branch & no issues with tabs

**Comment by XxUnkn0wnxX** [comment]
issue resolved in develop branch... 3eb3cc4b1d9e685ed0a03c14a518acb919a3d19c

just need master to be updated
