### ISSUE TITLE
[APP SUBMITTED]: KeyError: 'backlog_search'

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [pymedusa/Medusa#7448]
### INFO
**Python Version**: `3.7.5 (default, Nov  1 2019, 02:16:23) [Clang 11.0.0 (clang-1100.0.33.8)]`
**Operating System**: `Darwin-19.0.0-x86_64-i386-64bit`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@fcb5a1969dcd4ea0b6fb4a9debbf60179b0bbf4b
**Link to Log**: https://gist.github.com/eb1b2912f593d5e8574e1b984384246e
### ERROR
<pre>
2019-12-05 17:41:37 ERROR    Thread_19 :: [fcb5a19] Exception generated: 'backlog_search'
Traceback (most recent call last):
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/fcb5a1969dcd4ea0b6fb4a9debbf60179b0bbf4b/medusa/server/web/core/base.py#L251">medusa/server/web/core/base.py</a>", line 251, in async_call
    result = function(**kwargs)
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/fcb5a1969dcd4ea0b6fb4a9debbf60179b0bbf4b/medusa/server/web/manage/searches.py#L26">medusa/server/web/manage/searches.py</a>", line 26, in index
    forcedSearchQueueLength=app.forced_search_queue_scheduler.action.queue_length(),
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/fcb5a1969dcd4ea0b6fb4a9debbf60179b0bbf4b/medusa/search/queue.py#L179">medusa/search/queue.py</a>", line 179, in queue_length
    length['backlog_search'] += 1
KeyError: 'backlog_search'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by XxUnkn0wnxX** [comment]
### INFO
**Python Version**: `3.7.5 (default, Nov  1 2019, 02:16:23) [Clang 11.0.0 (clang-1100.0.33.8)]`
**Operating System**: `Darwin-19.0.0-x86_64-i386-64bit`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@fcb5a1969dcd4ea0b6fb4a9debbf60179b0bbf4b
**Link to Log**: https://gist.github.com/0fd924dec748a93ef3584e18e4b6627b
### ERROR
<pre>
2019-12-05 17:43:41 ERROR    Thread_24 :: [fcb5a19] Exception generated: 'backlog_search'
Traceback (most recent call last):
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/fcb5a1969dcd4ea0b6fb4a9debbf60179b0bbf4b/medusa/server/web/core/base.py#L251">medusa/server/web/core/base.py</a>", line 251, in async_call
    result = function(**kwargs)
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/fcb5a1969dcd4ea0b6fb4a9debbf60179b0bbf4b/medusa/server/web/manage/searches.py#L26">medusa/server/web/manage/searches.py</a>", line 26, in index
    forcedSearchQueueLength=app.forced_search_queue_scheduler.action.queue_length(),
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/fcb5a1969dcd4ea0b6fb4a9debbf60179b0bbf4b/medusa/search/queue.py#L179">medusa/search/queue.py</a>", line 179, in queue_length
    length['backlog_search'] += 1
KeyError: 'backlog_search'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by XxUnkn0wnxX** [comment]
this happens when i try to go to Manage Searches page when there was something in the backlog.. disappointing that this is broken on master.

**Comment by XxUnkn0wnxX** [comment]
### INFO
**Python Version**: `3.7.5 (default, Nov  1 2019, 02:16:23) [Clang 11.0.0 (clang-1100.0.33.8)]`
**Operating System**: `Darwin-19.0.0-x86_64-i386-64bit`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@6456664611d1fe304d7e3118104dcac4cd607a25
**Link to Log**: https://gist.github.com/b1954bb9315bc610b131017c85de575d
### ERROR
<pre>
2019-12-05 17:49:48 ERROR    Thread_0 :: [6456664] Exception generated: 'backlog_search'
Traceback (most recent call last):
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/6456664611d1fe304d7e3118104dcac4cd607a25/medusa/server/web/core/base.py#L251">medusa/server/web/core/base.py</a>", line 251, in async_call
    result = function(**kwargs)
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/6456664611d1fe304d7e3118104dcac4cd607a25/medusa/server/web/manage/searches.py#L26">medusa/server/web/manage/searches.py</a>", line 26, in index
    forcedSearchQueueLength=app.forced_search_queue_scheduler.action.queue_length(),
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/6456664611d1fe304d7e3118104dcac4cd607a25/medusa/search/queue.py#L179">medusa/search/queue.py</a>", line 179, in queue_length
    length['backlog_search'] += 1
KeyError: 'backlog_search'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by XxUnkn0wnxX** [comment]
seems to be broken on develop branch as well..

To Reproduce:
have 2 episodes from different shows marked as snatched but never downloaded
then retry download, select no when the popup shows.
do this on 2 or more episodes to queue up in backlog, then go to Manage Searches, white page will only display & error in log.

**Comment by medariox** [comment]
Report once and wait for the fix. Avoid useless comments that waste our time.

**Comment by p0psicles** [comment]
tnx @XxUnkn0wnxX i'll look into it. Pls standby for testing out a fix when ready. Don't know when, as I have to also look into the show updater issues

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/7449

**Comment by XxUnkn0wnxX** [comment]
page doesn't display white anymore & error does not prop but it doesn't show any values in the manage searches page now. when following steps from reproduce to initiate manual backlogging it shows here as nothing is running.

![Screen Shot 2019-12-05 at 10 52 34 pm](https://user-images.githubusercontent.com/2242880/70233104-07298300-17b2-11ea-8c7f-db3075ce368e.jpg)

![Screen Shot 2019-12-05 at 10 52 51 pm](https://user-images.githubusercontent.com/2242880/70233119-0e509100-17b2-11ea-8fe4-c9717e9d9fa2.jpg)

@p0psicles 
+ i been getting another strange error since update Issue: #7235

**Comment by p0psicles** [comment]
@XxUnkn0wnxX with #7452 that should be fixed

**Comment by XxUnkn0wnxX** [comment]
yep all good now, but front end shows list page is still broken sigh in develop... i hope this fix for searches gets pushed to master soon or develop frontend home page is fixed in the near close future...

**Comment by p0psicles** [comment]
What do you mean, frond end shows list page is broken?

**Comment by XxUnkn0wnxX** [comment]
as described in issue #7428 @p0psicles that problem persists in develop still in the frontend home shows page, tabs missing & search/filter is broken still.

**Comment by rafi-d** [comment]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]`
**Operating System**: `Windows-10-10.0.17763`
**Locale**: `cp1255`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@fcb5a1969dcd4ea0b6fb4a9debbf60179b0bbf4b
**Link to Log**: https://gist.github.com/63f9c36c1c3c6ae9a8cc2226243855d7
### ERROR
<pre>
2019-12-05 21:39:27 ERROR    Thread_5 :: [fcb5a19] Exception generated: u'backlog_search'
Traceback (most recent call last):
  File "D:\Program Files\Medusa\Medusa\<a href="../blob/fcb5a1969dcd4ea0b6fb4a9debbf60179b0bbf4b/medusa/server/web/core/base.py#L251">medusa\server\web\core\base.py</a>", line 251, in async_call
    result = function(**kwargs)
  File "D:\Program Files\Medusa\Medusa\<a href="../blob/fcb5a1969dcd4ea0b6fb4a9debbf60179b0bbf4b/medusa/server/web/manage/searches.py#L26">medusa\server\web\manage\searches.py</a>", line 26, in index
    forcedSearchQueueLength=app.forced_search_queue_scheduler.action.queue_length(),
  File "D:\Program Files\Medusa\Medusa\<a href="../blob/fcb5a1969dcd4ea0b6fb4a9debbf60179b0bbf4b/medusa/search/queue.py#L179">medusa\search\queue.py</a>", line 179, in queue_length
    length['backlog_search'] += 1
KeyError: u'backlog_search'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
