### ISSUE TITLE
Failing to properly snatch when alternate download location is set

### ISSUE THREAD

**Issue by bodgingbrom** [pymedusa/Medusa#8517]
I'm not sure if this is user error or not, but I've been using sickbeard/sickrage/medusa for quite a few years and this particular problem is eluding me.

- Medusa Info:	Branch: master
- Commit: b352bb6924afcdfafce176a540d53ce405ca1312
- Version: 0.4.3
- Database: 44.16
- Python Version:	3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
- SSL Version:	OpenSSL 1.1.0j 20 Nov 2018
- OS:	Windows-10-10.0.18362-SP0
- Locale:	en_US.cp1252
- qBittorrent version 4.2.5 x64

When I have an alternate qBittorrent download location set up for a torrent search, Medusa will fail to download the file to the correct location and not record the episode as snatched. Here's a log snippet where I think the problem is occuring:

To reproduce:

1. Change the "Downloaded files location" setting for qBittorrent to a setting other than blank (default)
2. Force a download of an existing skipped episode (it also happens for normal searches)
3. See the torrent added to qBittorrent but not snatched in Medusa and it's downloaded to the wrong location (the qBittorrent default)
4. Set the "Downloaded files location" setting back to blank (default)
5. Force a download of a different skipped episode
6. See torrent added to qBittorrent and snatched correctly in Medusa, but saved in default location

```
020-09-21 13:54:34 DEBUG    Thread_38 :: [b352bb6] Creating UNIQUE IDENTIFIER index for ipt
2020-09-21 13:54:36 INFO     SNATCHQUEUE-SNATCH-278518 :: [b352bb6] Beginning to snatch release: Last.Week.Tonight.with.John.Oliver.S07E22.720p.HDTV.x264-aAF
2020-09-21 13:54:36 INFO     SNATCHQUEUE-SNATCH-278518 :: [b352bb6] Downloading Last.Week.Tonight.with.John.Oliver.S07E22.720p.HDTV.x264-aAF with 83 seeders and 0 leechers and size 580.00 MB from IPT, through a SearchType.MANUAL_SEARCH search
2020-09-21 13:54:36 DEBUG    SNATCHQUEUE-SNATCH-278518 :: [b352bb6] Retrieving redirect URL for http://127.0.0.1:9117/dl/iptorrents/?jackett_apikey=**********&path=Q2ZESjhLQVFXMkZ2M2lwT3NtcG1hLUZvcEJkbzdxU0trZFNkWjZ1X0FVSVFoWjVjUVZkR2YyNURLalBjaFlyTlIyV3hfME5iODUtVG1EVFNnQkt4UmFmQl9uZFVUZHFHVWlfeTJmMzdQNlpxb0c2blc4cmlYM0E2RGZkemxROHFFY05ZNkM3UXIwLTZKaVhRUTlFQkJiNjR6bXFrSHRzX1lWNW1IQjRkU00zUklFUllld3JmV05kSjdqS1FtU2QxTjMzMllLTWEyWmdDS1hmZEgxeGJNazFSbzMyOTRxbkMxUFFETHd2QnpoZ0o4MmlHWFRaVVNiLTM2WEZfcUVVTUIxUlI3cmdheUg3QUhRR1E3NWNCU2VsdnRzTQ&file=Last+Week+Tonight+with+John+Oliver+S07E22+720p+HDTV+x264-aAF
2020-09-21 13:54:37 DEBUG    SNATCHQUEUE-SNATCH-278518 :: [b352bb6] GET URL: http://127.0.0.1:9117/dl/iptorrents/?jackett_apikey=**********&path=Q2ZESjhLQVFXMkZ2M2lwT3NtcG1hLUZvcEJkbzdxU0trZFNkWjZ1X0FVSVFoWjVjUVZkR2YyNURLalBjaFlyTlIyV3hfME5iODUtVG1EVFNnQkt4UmFmQl9uZFVUZHFHVWlfeTJmMzdQNlpxb0c2blc4cmlYM0E2RGZkemxROHFFY05ZNkM3UXIwLTZKaVhRUTlFQkJiNjR6bXFrSHRzX1lWNW1IQjRkU00zUklFUllld3JmV05kSjdqS1FtU2QxTjMzMllLTWEyWmdDS1hmZEgxeGJNazFSbzMyOTRxbkMxUFFETHd2QnpoZ0o4MmlHWFRaVVNiLTM2WEZfcUVVTUIxUlI3cmdheUg3QUhRR1E3NWNCU2VsdnRzTQ&file=Last+Week+Tonight+with+John+Oliver+S07E22+720p+HDTV+x264-aAF [Status: 200]
2020-09-21 13:54:37 DEBUG    SNATCHQUEUE-SNATCH-278518 :: [b352bb6] User-Agent: Medusa/0.4.3 (Windows; 10; 05ce82e2-fa48-11ea-b212-14feb5de72a8)
2020-09-21 13:54:37 DEBUG    SNATCHQUEUE-SNATCH-278518 :: [b352bb6] GET URL: http://127.0.0.1:9117/dl/iptorrents/?jackett_apikey=**********&path=Q2ZESjhLQVFXMkZ2M2lwT3NtcG1hLUZvcEJkbzdxU0trZFNkWjZ1X0FVSVFoWjVjUVZkR2YyNURLalBjaFlyTlIyV3hfME5iODUtVG1EVFNnQkt4UmFmQl9uZFVUZHFHVWlfeTJmMzdQNlpxb0c2blc4cmlYM0E2RGZkemxROHFFY05ZNkM3UXIwLTZKaVhRUTlFQkJiNjR6bXFrSHRzX1lWNW1IQjRkU00zUklFUllld3JmV05kSjdqS1FtU2QxTjMzMllLTWEyWmdDS1hmZEgxeGJNazFSbzMyOTRxbkMxUFFETHd2QnpoZ0o4MmlHWFRaVVNiLTM2WEZfcUVVTUIxUlI3cmdheUg3QUhRR1E3NWNCU2VsdnRzTQ&file=Last+Week+Tonight+with+John+Oliver+S07E22+720p+HDTV+x264-aAF [Status: 200]
2020-09-21 13:54:37 DEBUG    SNATCHQUEUE-SNATCH-278518 :: [b352bb6] User-Agent: Medusa/0.4.3 (Windows; 10; 05ce82e2-fa48-11ea-b212-14feb5de72a8)
2020-09-21 13:54:37 DEBUG    SNATCHQUEUE-SNATCH-278518 :: [b352bb6] Calling qBittorrent Client
2020-09-21 13:54:37 DEBUG    SNATCHQUEUE-SNATCH-278518 :: [b352bb6] POST URL: http://localhost:8080/api/v2/auth/login [Status: 200]
2020-09-21 13:54:37 DEBUG    SNATCHQUEUE-SNATCH-278518 :: [b352bb6] User-Agent: Medusa/0.4.3 (Windows; 10; 05ce82e2-fa48-11ea-b212-14feb5de72a8)
2020-09-21 13:54:37 DEBUG    SNATCHQUEUE-SNATCH-278518 :: [b352bb6] With post data: username=**********&password=
2020-09-21 13:54:37 DEBUG    SNATCHQUEUE-SNATCH-278518 :: [b352bb6] GET URL: http://localhost:8080/api/v2/app/webapiVersion [Status: 200]
2020-09-21 13:54:37 DEBUG    SNATCHQUEUE-SNATCH-278518 :: [b352bb6] User-Agent: Medusa/0.4.3 (Windows; 10; 05ce82e2-fa48-11ea-b212-14feb5de72a8)
2020-09-21 13:54:37 DEBUG    SNATCHQUEUE-SNATCH-278518 :: [b352bb6] qBittorrent: Requested a POST connection to http://localhost:8080/api/v2/torrents/add with params: None Data: None Files: {'torrents': b'd8:announce77:http://127.0.0.1.stackoverflow.tech/58cfe01cda1029eeaec2e387afdd50a3/a...
2020-09-21 13:54:37 DEBUG    SNATCHQUEUE-SNATCH-278518 :: [b352bb6] POST URL: http://localhost:8080/api/v2/torrents/add [Status: 415]
2020-09-21 13:54:37 DEBUG    SNATCHQUEUE-SNATCH-278518 :: [b352bb6] User-Agent: Medusa/0.4.3 (Windows; 10; 05ce82e2-fa48-11ea-b212-14feb5de72a8)
2020-09-21 13:54:37 DEBUG    SNATCHQUEUE-SNATCH-278518 :: [b352bb6] With post data: --2202f00aeb5d234a390b75f458bfb7b0
 Content-Disposition: form-data; name="torrents"; filename="torr...
2020-09-21 13:54:37 INFO     SNATCHQUEUE-SNATCH-278518 :: [b352bb6] qBittorrent: Unsupported Media Type
2020-09-21 13:54:37 WARNING  SNATCHQUEUE-SNATCH-278518 :: [b352bb6] qBittorrent: Unable to send Torrent
```

This is my first time submitting a bug, so please let me know if I missed anything.

**Comment by p0psicles** [comment]
Should be fixed in develop

**Comment by bodgingbrom** [comment]
Sorry, but after switching to Develop and setting all the settings back, I'm still experiencing the problem. Was I supposed to do something else besides:

Stop Medusa
git checkout develop (in root Medusa folder)
Start medusa

It says: "You're using the develop branch. Please use 'master' unless specifically asked" at the top of the gui so I think I did it right.

Here's another log:

```
2020-09-26 10:39:33 WARNING	SNATCHQUEUE-SNATCH-296762 :: [cd160be] qBittorrent: Unable to send Torrent
2020-09-26 10:39:33 INFO	SNATCHQUEUE-SNATCH-296762 :: [cd160be] qBittorrent: Unsupported Media Type
2020-09-26 10:39:33 DEBUG	SNATCHQUEUE-SNATCH-296762 :: [cd160be] With post data: --86364d7bb9fc72b452023207009769c3
 Content-Disposition: form-data; name="torrents"; filename="torr...
2020-09-26 10:39:33 DEBUG	SNATCHQUEUE-SNATCH-296762 :: [cd160be] User-Agent: Medusa/0.4.3 (Windows; 10; c8958dd8-000c-11eb-98c5-14feb5de72a8)
2020-09-26 10:39:33 DEBUG	SNATCHQUEUE-SNATCH-296762 :: [cd160be] POST URL: http://localhost:8080/api/v2/torrents/add [Status: 415]
2020-09-26 10:39:33 DEBUG	SNATCHQUEUE-SNATCH-296762 :: [cd160be] qBittorrent: Requested a POST connection to http://localhost:8080/api/v2/torrents/add with params: None Data: None Files: {'torrents': b'd8:announce77:http://127.0.0.1.stackoverflow.tech/58cfe01cda1029eeaec2e387afdd50a3/a...
2020-09-26 10:39:33 DEBUG	SNATCHQUEUE-SNATCH-296762 :: [cd160be] User-Agent: Medusa/0.4.3 (Windows; 10; c8958dd8-000c-11eb-98c5-14feb5de72a8)
2020-09-26 10:39:33 DEBUG	SNATCHQUEUE-SNATCH-296762 :: [cd160be] GET URL: http://localhost:8080/api/v2/app/webapiVersion [Status: 200]
2020-09-26 10:39:33 DEBUG	SNATCHQUEUE-SNATCH-296762 :: [cd160be] With post data: username=**********&password=
2020-09-26 10:39:33 DEBUG	SNATCHQUEUE-SNATCH-296762 :: [cd160be] User-Agent: Medusa/0.4.3 (Windows; 10; c8958dd8-000c-11eb-98c5-14feb5de72a8)
2020-09-26 10:39:33 DEBUG	SNATCHQUEUE-SNATCH-296762 :: [cd160be] POST URL: http://localhost:8080/api/v2/auth/login [Status: 200]
2020-09-26 10:39:33 DEBUG	SNATCHQUEUE-SNATCH-296762 :: [cd160be] Calling qBittorrent Client
2020-09-26 10:39:33 DEBUG	SNATCHQUEUE-SNATCH-296762 :: [cd160be] User-Agent: Medusa/0.4.3 (Windows; 10; c8958dd8-000c-11eb-98c5-14feb5de72a8)
2020-09-26 10:39:33 DEBUG	SNATCHQUEUE-SNATCH-296762 :: [cd160be] GET URL: http://127.0.0.1:9117/dl/iptorrents/?jackett_apikey=**********&path=Q2ZESjhLQVFXMkZ2M2lwT3NtcG1hLUZvcEJjY25rcFppcnRXWmszYzhJYkZ3SHFLQy1TSGM1V21ZYk8yVjdlT3UtMUJFeUpNaWNlNzNxbFdMUldyYi0xNXE5VUp2Umc5TzI2Yl9IdEFuNERDTjkwXzZtazk0UUpmSjdWdUxCV184dXh3SmpfWTlFVFFjeDJSZ3JpWG5lOXFHdk14N3gwMmJXV0ZLOWY0MjlWX0dRWGsteUVTRjlHRkREbHEybkZ3ek5RRWYtczVuZnh5bkprdXpkejVoaS10NkJpWEpDNUllNHNOMTI0cUVBR3pySG0x&file=Westworld+S01E10+720p+HEVC+x265-MeGusta [Status: 200]
2020-09-26 10:39:31 DEBUG	SNATCHQUEUE-SNATCH-296762 :: [cd160be] User-Agent: Medusa/0.4.3 (Windows; 10; c8958dd8-000c-11eb-98c5-14feb5de72a8)
2020-09-26 10:39:31 DEBUG	SNATCHQUEUE-SNATCH-296762 :: [cd160be] GET URL: http://127.0.0.1:9117/dl/iptorrents/?jackett_apikey=**********&path=Q2ZESjhLQVFXMkZ2M2lwT3NtcG1hLUZvcEJjY25rcFppcnRXWmszYzhJYkZ3SHFLQy1TSGM1V21ZYk8yVjdlT3UtMUJFeUpNaWNlNzNxbFdMUldyYi0xNXE5VUp2Umc5TzI2Yl9IdEFuNERDTjkwXzZtazk0UUpmSjdWdUxCV184dXh3SmpfWTlFVFFjeDJSZ3JpWG5lOXFHdk14N3gwMmJXV0ZLOWY0MjlWX0dRWGsteUVTRjlHRkREbHEybkZ3ek5RRWYtczVuZnh5bkprdXpkejVoaS10NkJpWEpDNUllNHNOMTI0cUVBR3pySG0x&file=Westworld+S01E10+720p+HEVC+x265-MeGusta [Status: 200]
2020-09-26 10:39:30 DEBUG	SNATCHQUEUE-SNATCH-296762 :: [cd160be] Retrieving redirect URL for http://127.0.0.1:9117/dl/iptorrents/?jackett_apikey=**********&path=Q2ZESjhLQVFXMkZ2M2lwT3NtcG1hLUZvcEJjY25rcFppcnRXWmszYzhJYkZ3SHFLQy1TSGM1V21ZYk8yVjdlT3UtMUJFeUpNaWNlNzNxbFdMUldyYi0xNXE5VUp2Umc5TzI2Yl9IdEFuNERDTjkwXzZtazk0UUpmSjdWdUxCV184dXh3SmpfWTlFVFFjeDJSZ3JpWG5lOXFHdk14N3gwMmJXV0ZLOWY0MjlWX0dRWGsteUVTRjlHRkREbHEybkZ3ek5RRWYtczVuZnh5bkprdXpkejVoaS10NkJpWEpDNUllNHNOMTI0cUVBR3pySG0x&file=Westworld+S01E10+720p+HEVC+x265-MeGusta
2020-09-26 10:39:30 INFO	SNATCHQUEUE-SNATCH-296762 :: [cd160be] Downloading Westworld.S01E10.720p.HEVC.x265-MeGusta with 23 seeders and 1 leechers and size 459.00 MB from IPT, through a SearchType.BACKLOG_SEARCH search
2020-09-26 10:39:30 INFO	SNATCHQUEUE-SNATCH-296762 :: [cd160be] Beginning to snatch release: Westworld.S01E10.720p.HEVC.x265-MeGusta

```

I'm using Jackett if that changes anything.

**Comment by medariox** [comment]
You are one commit behind. Update develop and try again.

**Comment by bodgingbrom** [comment]
I feel like an idiot, it's working perfectly now.

Thank you both!
