### ISSUE TITLE
IPTorrents layout bug

### ISSUE THREAD

**Issue by bpvarsity** [pymedusa/Medusa#8968]
IPtorrents layout bug is still present. When doing a manual search it is pulling the file count instead of the seed count. 
See image below. THis is messing everything up as it will snatch files with 0 seeds because it thinks it has 400(files)

![image](https://user-images.githubusercontent.com/2837098/103939913-2780eb00-50f2-11eb-87c0-b9518b50f550.png)

Medusa Info: | Branch: masterCommit: 1c1d3279ea1c3bb891b8581671e21543aea00c8cVersion: 0.5.1
-- | --

**Comment by medariox** [comment]
Working fine here. Delete the cache or force update the results.

**Comment by bpvarsity** [comment]
Done that many times now and it does it for every show. Will try again

**Comment by bpvarsity** [comment]
> Working fine here. Delete the cache or force update the results.

Cleared cache and forced update and still same issue. What can I try now?

**Comment by bpvarsity** [comment]
It's also doing it with automatic searches as well. Adding torrents that it thinks has X number of seeders but in reality, its 0 and still thinking file counts are seeders.

**Comment by medariox** [comment]
Not sure. Maybe you're using an old layout or your Medusa is not really up to date.

**Comment by bpvarsity** [comment]
> Not sure. Maybe you're using an old layout or your Medusa is not really up to date.

Didn't know there was any different layouts. Using just the stock install of Medusa via Swizzin. How can I force update Medusa to see if its really not updated like it says it is?

**Comment by bpvarsity** [comment]
I switched to the development branch but still the same issue.

**Comment by medariox** [comment]
https://github.com/pymedusa/Medusa/pull/8675
It was fixed. No need to use develop. Make sure you have the changes of the PR.

**Comment by bpvarsity** [comment]
I pulled the master again with the Medusa button in General/Advanced. Still having the issue so not sure what is going on ugh
