### ISSUE TITLE
show won't remove

### ISSUE THREAD

**Issue by dsm1212** [pymedusa/Medusa#9553]
**Describe the bug**
I select remove from the show detail window and visually the app goes through the normal remove and returns to the show list. But the show is still in the list. If I go to the details window again, the episode details are gone. If I try to remove again the removal box which comes up says "none" as the show name. Removing again results in an all white page. I return to the show list and it's still there unchanged.

**To Reproduce**
Remove the show (One of mine like this is Gold Digger from the bbc).

**Expected behavior**
The show should disappear from the show list.

**Medusa (please complete the following information):**
Docker image from linuxserver with latest tag.

Medusa Info: | Branch:&nbsp;masterCommit:&nbsp;UnknownVersion:&nbsp;0.5.12Database:&nbsp;44.18
-- | --
Python Version: | 3.8.10 (default, May 6 2021, 06:30:44) [GCC 9.3.0]
SSL Version: | OpenSSL 1.1.1k 25 Mar 2021
OS: | Linux-5.10.0-0.bpo.4-amd64-x86_64-with
Locale: | en_US.UTF-8

**Debug logs (at least 50 lines):**
<details>
2021-05-17 21:29:55 INFO     SHOWQUEUE-REMOVE-SHOW :: [] 364389: Removing Gold Digger
2021-05-17 21:29:55 DEBUG    SHOWQUEUE-REMOVE-SHOW :: [] Transaction with 5 queries executed
2021-05-17 21:29:55 INFO     SHOWQUEUE-REMOVE-SHOW :: [] 364389: Attempt to delete show folder /tv/Gold Digger
2021-05-17 21:29:55 INFO     SHOWQUEUE-REMOVE-SHOW :: [] 364389: delete show folder /tv/Gold Digger
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 80349: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 80349: Found previous aired episode number S07E12
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 80349: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 80349: Found previous aired episode number S07E12
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 80349: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 80349: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 121361: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 121361: Found previous aired episode number S00E55
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 121361: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 121361: Found previous aired episode number S00E55
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 121361: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 121361: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 78804: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 78804: Found previous aired episode number S00E157
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 78804: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 78804: Found previous aired episode number S00E157
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 78804: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 78804: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 70386: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 70386: Found previous aired episode number S00E03
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 70386: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 70386: Found previous aired episode number S00E03
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 70386: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 70386: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 247897: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 247897: Found previous aired episode number S08E12
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 247897: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 247897: Found previous aired episode number S08E12
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 247897: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 247897: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 1483: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 1483: Found previous aired episode number S00E01
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 1483: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 1483: Found previous aired episode number S00E01
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 1483: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 1483: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 43: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 43: Found previous aired episode number S05E12
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 43: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 43: Found previous aired episode number S05E12
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 43: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 43: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 150: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 150: Found previous aired episode number S11E12
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 150: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 150: Found previous aired episode number S11E12
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 150: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 150: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 176941: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 176941: Found previous aired episode number S04E03
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 176941: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 176941: Found previous aired episode number S04E03
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 176941: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 176941: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 78901: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 78901: Found previous aired episode number S15E20
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 78901: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 78901: Found previous aired episode number S15E20
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 78901: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 78901: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 470: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 470: Found previous aired episode number S01E17
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 470: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 470: Found previous aired episode number S01E17
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 470: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 470: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 153021: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 153021: Found previous aired episode number S10E22
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 153021: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 153021: Found previous aired episode number S10E22
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 270633: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 270633: Found previous aired episode number S03E08
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 270633: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 270633: Found previous aired episode number S03E08
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 270633: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 270633: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 75932: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 75932: Found previous aired episode number S00E35
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 75932: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 75932: Found previous aired episode number S00E35
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 75932: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 75932: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 320: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 320: Found previous aired episode number S03E06
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 320: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 320: Found previous aired episode number S03E06
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 320: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 320: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 295759: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 295759: Found previous aired episode number S06E07
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 295759: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 295759: Found previous aired episode number S06E07
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 328711: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 328711: Found previous aired episode number S03E13
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 328711: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 328711: Found previous aired episode number S03E13
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 328711: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 328711: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 321239: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 321239: Found previous aired episode number S04E05
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 321239: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 321239: Found previous aired episode number S04E05
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 82701: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 82701: Found previous aired episode number S14E10
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 82701: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 82701: Found previous aired episode number S14E10
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 82701: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 82701: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 62117: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 62117: Found previous aired episode number S07E08
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 62117: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 62117: Found previous aired episode number S07E08
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 263365: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 263365: Found previous aired episode number S07E13
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 263365: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 263365: Found previous aired episode number S07E13
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 263365: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 263365: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 270439: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 270439: Found previous aired episode number S05E11
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 270439: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 270439: Found previous aired episode number S05E11
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 270439: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 270439: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 305719: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 305719: Found previous aired episode number S00E04
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 305719: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 305719: Found previous aired episode number S00E04
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 305719: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 305719: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 321448: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 321448: Found previous aired episode number S03E06
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 321448: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 321448: Found previous aired episode number S03E06
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 321448: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 321448: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 290853: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 290853: Found previous aired episode number S06E13
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 290853: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 290853: Found previous aired episode number S06E13
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 279121: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 279121: Found previous aired episode number S07E09
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 279121: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 279121: Found previous aired episode number S07E09
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 351291: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 351291: Found previous aired episode number S02E10
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 351291: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 351291: Found previous aired episode number S02E10
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 351291: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 351291: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 364093: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 364093: Found previous aired episode number S01E10
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 364093: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 364093: Found previous aired episode number S01E10
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 364093: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 364093: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 328634: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 328634: Found previous aired episode number S04E16
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 328634: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 328634: Found previous aired episode number S04E16
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 368126: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 368126: Found previous aired episode number S02E10
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 368126: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 368126: Found previous aired episode number S02E10
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 368126: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 368126: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 360295: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 360295: Found previous aired episode number S02E07
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 360295: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 360295: Found previous aired episode number S02E07
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 360295: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 360295: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 34650: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 34650: Found previous aired episode number S02E13
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 34650: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 34650: Found previous aired episode number S02E13
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 361753: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 361753: Found previous aired episode number S02E08
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 361753: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 361753: Found previous aired episode number S02E08
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 361753: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 361753: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 383203: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 383203: Found previous aired episode number S01E10
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 383203: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 383203: Found previous aired episode number S01E10
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 366625: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 366625: Found previous aired episode number S01E08
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 366625: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 366625: Found previous aired episode number S01E08
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 366625: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 366625: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 3144: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 3144: Found previous aired episode number S04E10
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 3144: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 3144: Found previous aired episode number S04E10
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 3144: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 3144: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 256111: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 256111: Found previous aired episode number S05E18
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 256111: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 256111: Found previous aired episode number S05E18
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 256111: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 256111: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 311898: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 311898: Found previous aired episode number S01E12
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 311898: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 311898: Found previous aired episode number S01E12
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 311898: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 311898: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 35: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 35: Found previous aired episode number S04E06
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 35: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 35: Found previous aired episode number S04E06
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 35: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 35: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 349271: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 349271: Found previous aired episode number S03E09
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 349271: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 349271: Found previous aired episode number S03E09
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 326866: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 326866: Found previous aired episode number S03E08
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 326866: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 326866: Found previous aired episode number S03E08
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 326866: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 326866: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 78192: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 78192: Found previous aired episode number S01E22
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 78192: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 78192: Found previous aired episode number S01E22
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 78192: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 78192: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 365069: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 365069: Found previous aired episode number S01E10
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 365069: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 365069: Found previous aired episode number S01E10
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 295760: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 295760: Found previous aired episode number S06E03
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 295760: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 295760: Found previous aired episode number S06E03
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 364865: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 364865: Found previous aired episode number S02E05
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 364865: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 364865: Found previous aired episode number S02E05
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 364865: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 364865: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 357864: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 357864: Found previous aired episode number S00E01
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 357864: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 357864: Found previous aired episode number S00E01
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 357864: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 357864: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 319742: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 319742: Found previous aired episode number S04E04
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 319742: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 319742: Found previous aired episode number S04E04
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 319742: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 319742: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 351282: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 351282: Found previous aired episode number S02E13
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 351282: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 351282: Found previous aired episode number S02E13
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 351282: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 351282: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 73965: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 73965: Found previous aired episode number S03E18
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 73965: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 73965: Found previous aired episode number S03E18
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 73965: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 73965: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 301057: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 301057: Found previous aired episode number S04E06
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 301057: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 301057: Found previous aired episode number S04E06
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 301057: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 301057: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 358915: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 358915: Found previous aired episode number S02E01
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 358915: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 358915: Found previous aired episode number S02E01
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 358915: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 358915: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 97331: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 97331: Found previous aired episode number S02E13
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 97331: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 97331: Found previous aired episode number S02E13
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 97331: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 97331: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 360893: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 360893: Found previous aired episode number S01E05
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 360893: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 360893: Found previous aired episode number S01E05
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 360893: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 360893: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 363998: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 363998: Found previous aired episode number S02E10
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 363998: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 363998: Found previous aired episode number S02E10
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 363998: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 363998: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 367018: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 367018: Found previous aired episode number S01E06
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 367018: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 367018: Found previous aired episode number S01E06
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 367018: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 367018: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 350667: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 350667: Found previous aired episode number S03E13
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 350667: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 350667: Found previous aired episode number S03E13
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 349309: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 349309: Found previous aired episode number S03E12
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 349309: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 349309: Found previous aired episode number S03E12
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 341164: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 341164: Found previous aired episode number S03E10
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 341164: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 341164: Found previous aired episode number S03E10
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 367534: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 367534: Found previous aired episode number S03E10
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 367534: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 367534: Found previous aired episode number S03E10
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 367534: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 367534: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 361563: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 361563: Found previous aired episode number S01E10
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 361563: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 361563: Found previous aired episode number S01E10
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 361563: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 361563: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 362829: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 362829: Found previous aired episode number S02E03
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 362829: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 362829: Found previous aired episode number S02E03
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 360927: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 360927: Found previous aired episode number S01E08
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 360927: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 360927: Found previous aired episode number S01E08
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 360927: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 360927: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 340959: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 340959: Found previous aired episode number S03E08
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 340959: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 340959: Found previous aired episode number S03E08
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 340959: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 340959: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 365480: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 365480: Found previous aired episode number S01E10
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 365480: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 365480: Found previous aired episode number S01E10
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 365480: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 365480: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 328569: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 328569: Found previous aired episode number S04E13
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 328569: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 328569: Found previous aired episode number S04E13
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 237831: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 237831: Found previous aired episode number S07E07
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 237831: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 237831: Found previous aired episode number S07E07
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 237831: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 237831: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 361315: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 361315: Found previous aired episode number S02E14
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 361315: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 361315: Found previous aired episode number S02E14
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 361315: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 361315: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 371242: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 371242: Found previous aired episode number S01E10
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 371242: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 371242: Found previous aired episode number S01E10
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 371242: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 371242: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 363194: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 363194: Found previous aired episode number S01E08
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 363194: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 363194: Found previous aired episode number S01E08
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 363194: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 363194: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 379531: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 379531: Found previous aired episode number S01E08
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 379531: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 379531: Found previous aired episode number S01E08
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 379531: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 379531: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 362004: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 362004: Found previous aired episode number S01E10
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 362004: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 362004: Found previous aired episode number S01E10
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 361565: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 361565: Found previous aired episode number S01E08
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 361565: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 361565: Found previous aired episode number S01E08
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 361565: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 361565: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 356202: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 356202: Found previous aired episode number S02E10
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 356202: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 356202: Found previous aired episode number S02E10
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 356202: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 356202: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 361566: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 361566: Found previous aired episode number S02E10
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 361566: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 361566: Found previous aired episode number S02E10
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 361566: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 361566: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 351527: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 351527: Found previous aired episode number S01E08
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 351527: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 351527: Found previous aired episode number S01E08
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 351527: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 351527: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 28723: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 28723: Found previous aired episode number S01E05
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 28723: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 28723: Found previous aired episode number S01E05
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 28723: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 28723: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 368188: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 368188: Found previous aired episode number S01E10
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 368188: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 368188: Found previous aired episode number S01E10
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 79168: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 79168: Found previous aired episode number S10E18
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 79168: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 79168: Found previous aired episode number S10E18
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 79168: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 79168: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 339512: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 339512: Found previous aired episode number S02E08
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 339512: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 339512: Found previous aired episode number S02E08
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 339512: Finding the episode which airs next
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 339512: Could not find a next episode
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 372787: Finding the episode which aired last
2021-05-17 21:29:58 DEBUG    APIv2-Thread_0 :: [] 372787: Found previous aired episode number S01E10
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 372787: Finding the episode which aired last
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 372787: Found previous aired episode number S01E10
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 372787: Finding the episode which airs next
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 372787: Could not find a next episode
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 326559: Finding the episode which aired last
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 326559: Found previous aired episode number S03E08
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 326559: Finding the episode which aired last
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 326559: Found previous aired episode number S03E08
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 326559: Finding the episode which airs next
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 326559: Could not find a next episode
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 295778: Finding the episode which aired last
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 295778: Found previous aired episode number S04E13
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 295778: Finding the episode which aired last
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 295778: Found previous aired episode number S04E13
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 295778: Finding the episode which airs next
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 295778: Could not find a next episode
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 362392: Finding the episode which aired last
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 362392: Found previous aired episode number S01E09
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 362392: Finding the episode which aired last
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 362392: Found previous aired episode number S01E09
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 362392: Finding the episode which airs next
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 362392: Could not find a next episode
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 376395: Finding the episode which aired last
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 376395: Found previous aired episode number S01E09
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 376395: Finding the episode which aired last
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 376395: Found previous aired episode number S01E09
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 368166: Finding the episode which aired last
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 368166: Found previous aired episode number S01E10
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 368166: Finding the episode which aired last
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 368166: Found previous aired episode number S01E10
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 368166: Finding the episode which airs next
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 368166: Could not find a next episode
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 345831: Finding the episode which aired last
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 345831: Found previous aired episode number S03E13
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 345831: Finding the episode which aired last
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 345831: Found previous aired episode number S03E13
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 345831: Finding the episode which airs next
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 345831: Could not find a next episode
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 370112: Finding the episode which aired last
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 370112: Found previous aired episode number S01E05
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 370112: Finding the episode which aired last
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 370112: Found previous aired episode number S01E05
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 364315: Finding the episode which aired last
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 364315: Found previous aired episode number S01E06
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 364315: Finding the episode which aired last
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 364315: Found previous aired episode number S01E06
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 364315: Finding the episode which airs next
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 364315: Could not find a next episode
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 368643: Finding the episode which aired last
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 368643: Found previous aired episode number S01E10
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 368643: Finding the episode which aired last
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 368643: Found previous aired episode number S01E10
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 368643: Finding the episode which airs next
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 368643: Could not find a next episode
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 369414: Finding the episode which aired last
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 369414: Found previous aired episode number S01E08
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 369414: Finding the episode which aired last
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 369414: Found previous aired episode number S01E08
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 369414: Finding the episode which airs next
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 369414: Could not find a next episode
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 292745: Finding the episode which aired last
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 292745: Found previous aired episode number S03E10
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 292745: Finding the episode which aired last
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 292745: Found previous aired episode number S03E10
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 292745: Finding the episode which airs next
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 292745: Could not find a next episode
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 311714: Finding the episode which aired last
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 311714: Found previous aired episode number S05E14
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 311714: Finding the episode which aired last
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 311714: Found previous aired episode number S05E14
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 378023: Finding the episode which aired last
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 378023: Found previous aired episode number S01E15
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 378023: Finding the episode which aired last
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 378023: Found previous aired episode number S01E15
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 349358: Finding the episode which aired last
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 349358: Found previous aired episode number S03E19
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 349358: Finding the episode which aired last
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 349358: Found previous aired episode number S03E19
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 382801: Finding the episode which aired last
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 382801: Found previous aired episode number S01E12
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 382801: Finding the episode which aired last
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 382801: Found previous aired episode number S01E12
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 361732: Finding the episode which aired last
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 361732: Found previous aired episode number S02E13
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 361732: Finding the episode which aired last
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 361732: Found previous aired episode number S02E13
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 361732: Finding the episode which airs next
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 361732: Could not find a next episode
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 349272: Finding the episode which aired last
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 349272: Found previous aired episode number S03E11
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 349272: Finding the episode which aired last
2021-05-17 21:29:59 DEBUG    APIv2-Thread_0 :: [] 349272: Found previous aired episode number S03E11
</details>

**Additional context**
Oddly, just once I was able to re-add a show like this and then successfully delete it. This one I cannot get rid of.

**Comment by dsm1212** [comment]
I didn't notice but I have quite a few deleted shows on my show list which are truncated like this and can't be removed. I guess maybe a number of removes did not work correctly and I never noticed. There must be a code path where something which creates an entry on the show list doesn't get "removed".

**Comment by dsm1212** [comment]
So, I can't quite explain this but it cleared up. On a different client computer I saw the dead shows in the list so it is not a browser issue. I copied aside main.db so I could open it in sqlite3 and look for lingering entries. I didn't see the shows in the tables but when I went back to the browser, the shows are gone now. I see the code creates threads for the removes. Maybe they were blocked and for some reason finished finally? I wonder if there isn't a race condition on refreshing the main screen while the background remove is still going on, but that would not explain why they showed in multiple clients. I guess close unless you see something obvious wrong.

**Comment by dsm1212** [comment]
Ah, I'm sure you right. I thought some of the shows went away but I was on different browser. Each instance is showing ones that I deleted using that browser. Good luck. thanks

**Comment by p0psicles** [comment]
could you verify if it's resolved with PR #9563 (branch `feature/fix-remove-show`)

**Comment by dsm1212** [comment]
I'm sorry, is not so easy for me. I'm using the linuxserver docker and I don't see a develop image. Also the container does not have git installed so I could not even do something temporarily. Probably I need to do an overlay of the image but I'm not so savvy with docker yet.

**Comment by p0psicles** [comment]
Can't test with docker no

**Comment by p0psicles** [comment]
Should be fixed, can you confirm?

**Comment by dsm1212** [comment]
I've got 0.5.13 which shows the fix in the changelog and I'm sorry to say I still see these ghost deleted shows. It is a browser issue, I'm using chrome on a mac, but if I use safari the shows are not present. I think I deleted these after I took the last update but maybe not. Maybe I need to dump my browser cache?

**Comment by dsm1212** [comment]
I cleared cache and cookies for medusa. This cleared out the dead shows. Deleting a show works now. So I guess I was still having a bunch of crud in my cache.
